"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Circle, Loader2, Plus, ShieldCheck, UserCheck, UserX, Users } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Staff={id:number;full_name:string;email:string;role:"reviewer"|"publisher";active:boolean;two_factor_enabled:boolean;created_at:string};
type Onboarding={percent:number;completed:number;total:number;steps:{key:string;label:string;complete:boolean}[];subscription?:{status:string;usable:boolean;plan:{name:string;code:string;max_staff:number;max_campaigns_monthly:number;custom_domains:boolean;competition_certification:boolean}}|null};

export default function TenantTeamPage(){
 const router=useRouter();
 const [staff,setStaff]=useState<Staff[]>([]);
 const [onboarding,setOnboarding]=useState<Onboarding|null>(null);
 const [form,setForm]=useState({full_name:"",email:"",password:"",role:"reviewer" as "reviewer"|"publisher"});
 const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState("");

 async function load(){setLoading(true);setError("");try{const [team,setup]=await Promise.all([api<Staff[]>("/api/v1/tenant-admin/staff",{},true),api<Onboarding>("/api/v1/tenant-admin/onboarding",{},true)]);setStaff(team);setOnboarding(setup);}catch(e){setError(e instanceof Error?e.message:"Unable to load team workspace")}finally{setLoading(false)}}
 useEffect(()=>{const u=getSessionUser();if(!u?.is_tenant_admin){router.replace("/advertiser");return;}load();},[router]);

 async function addStaff(e:FormEvent){e.preventDefault();setBusy("create");setError("");setMessage("");try{await api("/api/v1/tenant-admin/staff",{method:"POST",body:JSON.stringify(form)},true);setForm({full_name:"",email:"",password:"",role:"reviewer"});setMessage("Staff account created.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create staff account")}finally{setBusy("")}}
 async function toggle(row:Staff){setBusy("staff-"+row.id);setError("");setMessage("");try{await api("/api/v1/tenant-admin/staff/"+row.id+"/state",{method:"PATCH",body:JSON.stringify({active:!row.active})},true);setMessage(row.active?"Staff account disabled.":"Staff account enabled.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update staff account")}finally{setBusy("")}}

 const activeCount=staff.filter(x=>x.active).length;
 return <main className="min-h-screen bg-[#f5f6fa] text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Page Team & Onboarding</h1><p className="text-xs text-slate-500">Complete portal setup and manage tenant reviewers and publishers.</p></div><Link href="/tenant-admin/settings" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-extrabold text-[#070a45]">Portal settings</Link></div></header>
  <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
   {error&&<div className="rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
   {message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}
   {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<>
    <section className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
     <div className="rounded-[1.6rem] bg-[#070a45] p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">Portal readiness</p><div className="mt-3 flex items-end gap-3"><span className="text-5xl font-black">{onboarding?.percent||0}%</span><span className="pb-1 text-sm text-white/50">{onboarding?.completed||0} of {onboarding?.total||0} setup areas complete</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[#e31545]" style={{width:`${onboarding?.percent||0}%`}}/></div><div className="mt-6 grid gap-2 sm:grid-cols-2">{onboarding?.steps.map(step=><div key={step.key} className="flex items-center gap-2 rounded-xl bg-white/5 p-3 text-sm font-bold">{step.complete?<CheckCircle2 size={16} className="text-emerald-400"/>:<Circle size={16} className="text-white/30"/>}{step.label}</div>)}</div></div>
     <div className="rounded-[1.6rem] border border-slate-200 bg-white p-6"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]"><ShieldCheck size={19}/></div><div><h2 className="font-black text-[#070a45]">Current tenant plan</h2><p className="mt-1 text-sm text-slate-500">{onboarding?.subscription?.plan.name||"No active plan"}</p></div></div>{onboarding?.subscription?<div className="mt-6 grid grid-cols-2 gap-3"><Limit label="Active staff" value={`${activeCount} / ${onboarding.subscription.plan.max_staff}`}/><Limit label="Campaign capacity" value={`${onboarding.subscription.plan.max_campaigns_monthly}/month`}/><Limit label="Custom domains" value={onboarding.subscription.plan.custom_domains?"Included":"Not included"}/><Limit label="Competition certification" value={onboarding.subscription.plan.competition_certification?"Included":"Not included"}/></div>:<p className="mt-6 rounded-xl bg-amber-50 p-4 text-sm font-semibold text-amber-800">Your portal needs an active tenant subscription before additional staff can be added.</p>}</div>
    </section>

    <section className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]">
     <form onSubmit={addStaff} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e31545]/10 text-[#e31545]"><Plus size={19}/></div><div><h2 className="font-black text-[#070a45]">Add Page staff</h2><p className="mt-1 text-sm text-slate-500">Create a reviewer or publisher account for this Page only.</p></div></div><div className="mt-5 space-y-4"><Field label="Full name"><input required value={form.full_name} onChange={e=>setForm(x=>({...x,full_name:e.target.value}))} placeholder="Staff member name"/></Field><Field label="Email"><input required type="email" value={form.email} onChange={e=>setForm(x=>({...x,email:e.target.value}))} placeholder="staff@example.com"/></Field><Field label="Role"><select value={form.role} onChange={e=>setForm(x=>({...x,role:e.target.value as "reviewer"|"publisher"}))}><option value="reviewer">Reviewer</option><option value="publisher">Publisher</option></select></Field><Field label="Temporary password"><input required minLength={10} type="password" value={form.password} onChange={e=>setForm(x=>({...x,password:e.target.value}))} placeholder="At least 10 characters"/></Field><button disabled={busy==="create"} className="h-12 w-full rounded-xl bg-[#070a45] text-sm font-extrabold text-white disabled:opacity-50">{busy==="create"?"Creating...":"Create staff account"}</button></div></form>

     <div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex items-center gap-3"><Users className="text-[#e31545]"/><div><h2 className="font-black text-[#070a45]">Page staff</h2><p className="mt-1 text-sm text-slate-500">{activeCount} active team member{activeCount===1?"":"s"}.</p></div></div></div>{staff.length===0?<div className="p-10 text-center text-sm text-slate-500">No reviewer or publisher accounts yet.</div>:<div className="divide-y divide-slate-100">{staff.map(row=><div key={row.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_auto] sm:items-center sm:px-6"><div><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold text-[#070a45]">{row.full_name}</p><span className={"rounded-full px-2 py-1 text-[10px] font-black "+(row.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{row.active?"Active":"Disabled"}</span><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-black text-blue-700">{row.role}</span>{row.two_factor_enabled&&<span className="rounded-full bg-violet-50 px-2 py-1 text-[10px] font-black text-violet-700">2FA</span>}</div><p className="mt-1 text-sm text-slate-500">{row.email}</p></div><button onClick={()=>toggle(row)} disabled={busy==="staff-"+row.id} className={"inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-xs font-extrabold disabled:opacity-50 "+(row.active?"border border-rose-200 text-rose-700":"bg-[#070a45] text-white")}>{row.active?<UserX size={15}/>:<UserCheck size={15}/>} {row.active?"Disable":"Enable"}</button></div>)}</div>}</div>
    </section>
   </>}
  </div>
 </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span><div className="rounded-xl border border-slate-200 bg-slate-50 px-3 [&_input]:h-12 [&_input]:w-full [&_input]:bg-transparent [&_input]:text-sm [&_input]:outline-none [&_select]:h-12 [&_select]:w-full [&_select]:bg-transparent [&_select]:text-sm [&_select]:outline-none">{children}</div></label>}
function Limit({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-sm font-extrabold text-[#070a45]">{value}</p></div>}
