"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Bell, CheckCircle2, Loader2 } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Notification={id:number;kind:string;title:string;message:string;read_at?:string|null;created_at:string};

export default function NotificationsPage(){
  const router=useRouter(); const [items,setItems]=useState<Notification[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState("");
  async function load(){setLoading(true);setError("");try{setItems(await api<Notification[]>("/api/v1/notifications",{},true));}catch(e){setError(e instanceof Error?e.message:"Unable to load notifications");}finally{setLoading(false)}}
  useEffect(()=>{const user=getSessionUser();if(!user||user.role!=="advertiser"){router.replace("/login");return;}load();},[router]);
  async function markRead(item:Notification){if(item.read_at)return;try{await api(`/api/v1/notifications/${item.id}/read`,{method:"POST"},true);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update notification")}}
  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-5xl items-center gap-4 px-4 sm:px-6"><Link href="/advertiser" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="font-black text-[#070a45]">Notifications</h1><p className="text-xs text-slate-500">Payment, editorial and publishing updates.</p></div></div></header><div className="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:items.length===0?<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><Bell className="mx-auto text-slate-300"/><h2 className="mt-4 font-black text-[#070a45]">No notifications yet</h2><p className="mt-2 text-sm text-slate-500">Updates will appear as your adverts move through payment, review and publishing.</p></div>:<section className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="divide-y divide-slate-100">{items.map(item=><button key={item.id} onClick={()=>markRead(item)} className={`flex w-full gap-4 p-5 text-left transition hover:bg-slate-50 ${item.read_at?"bg-white":"bg-indigo-50/45"}`}><div className={`mt-0.5 grid h-10 w-10 shrink-0 place-items-center rounded-xl ${item.read_at?"bg-slate-100 text-slate-400":"bg-[#070a45] text-white"}`}>{item.read_at?<CheckCircle2 size={17}/>:<Bell size={17}/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-black text-[#070a45]">{item.title}</p><span className="text-xs font-semibold text-slate-400">{new Date(item.created_at).toLocaleString()}</span></div><p className="mt-2 text-sm leading-6 text-slate-600">{item.message}</p><p className="mt-2 text-[10px] font-black uppercase tracking-wider text-slate-400">{item.kind.replaceAll("_"," ")}{item.read_at?" · read":" · click to mark read"}</p></div></button>)}</div></section>}</div></main>
}
