"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, CalendarDays, Clock3, ExternalLink } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Campaign={id:number;title:string;caption:string;status:string;preferred_publish_at:string|null;scheduled_publish_at:string|null;facebook_post_url:string|null;advertiser_id:number};
const statusStyle=(s:string)=>s==="published"?"bg-emerald-50 text-emerald-700":s==="scheduled"?"bg-blue-50 text-blue-700":s==="approved"?"bg-amber-50 text-amber-700":"bg-slate-100 text-slate-600";

export default function PublishingCalendar(){
  const [items,setItems]=useState<Campaign[]>([]); const [error,setError]=useState("");
  useEffect(()=>{const u=getSessionUser(); if(!u||u.role==="advertiser"){window.location.href="/login";return;} api<Campaign[]>("/api/v1/campaigns",{},true).then(setItems).catch(e=>setError(e.message));},[]);
  const calendar=useMemo(()=>items.filter(c=>["approved","scheduled","published"].includes(c.status)).sort((a,b)=>new Date(a.scheduled_publish_at||a.preferred_publish_at||a.id).getTime()-new Date(b.scheduled_publish_at||b.preferred_publish_at||b.id).getTime()),[items]);
  const grouped=useMemo(()=>{const map=new Map<string,Campaign[]>();calendar.forEach(c=>{const raw=c.scheduled_publish_at||c.preferred_publish_at;const key=raw?new Date(raw).toLocaleDateString("en-LS",{weekday:"long",day:"2-digit",month:"long",year:"numeric"}):"Unscheduled approved adverts";map.set(key,[...(map.get(key)||[]),c]);});return [...map.entries()];},[calendar]);
  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Publishing calendar</h1><p className="text-xs text-slate-500">Approved, scheduled and published Meloli adverts</p></div><CalendarDays className="text-[#e31545]"/></div></header>
  <div className="mx-auto max-w-[1200px] p-4 sm:p-6 lg:p-8"><section className="mb-6 rounded-[1.7rem] bg-[#070a45] p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">Editorial schedule</p><h2 className="mt-2 text-3xl font-black">{calendar.length} campaigns in the publishing pipeline</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/60">Only approved work appears here. Scheduling decisions remain under Meloli staff control before Facebook publishing.</p></div><div className="rounded-2xl bg-white/10 px-4 py-3 text-sm font-extrabold">{items.filter(i=>i.status==="scheduled").length} scheduled</div></div></section>
  {error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
  <div className="space-y-6">{grouped.map(([day,campaigns])=><section key={day} className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white"><div className="flex items-center gap-3 border-b border-slate-100 px-5 py-4"><CalendarDays size={18} className="text-[#e31545]"/><h3 className="font-black text-[#070a45]">{day}</h3></div><div className="divide-y divide-slate-100">{campaigns.map(c=>{const raw=c.scheduled_publish_at||c.preferred_publish_at;return <div key={c.id} className="grid gap-4 p-5 sm:grid-cols-[100px_1fr_auto] sm:items-center sm:px-6"><div className="flex items-center gap-2 text-sm font-black text-[#070a45]"><Clock3 size={15}/>{raw?new Date(raw).toLocaleTimeString("en-LS",{hour:"2-digit",minute:"2-digit"}):"TBD"}</div><div><div className="flex flex-wrap items-center gap-2"><p className="font-extrabold text-slate-900">{c.title}</p><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${statusStyle(c.status)}`}>{c.status.replaceAll("_"," ")}</span></div><p className="mt-1 line-clamp-2 text-sm text-slate-500">{c.caption}</p></div>{c.facebook_post_url?<a href={c.facebook_post_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-sm font-extrabold text-[#e31545]">View post <ExternalLink size={15}/></a>:<Link href={`/dashboard/campaigns/${c.id}`} className="text-sm font-extrabold text-[#e31545]">Open campaign</Link>}</div>})}</div></section>)}{grouped.length===0&&<div className="rounded-[1.5rem] border border-dashed border-slate-300 bg-white p-12 text-center"><CalendarDays className="mx-auto text-slate-300" size={34}/><p className="mt-4 font-black text-[#070a45]">No approved adverts yet</p><p className="mt-1 text-sm text-slate-500">Approved and scheduled campaigns will appear here automatically.</p></div>}</div></div></main>
}
