"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Copy, ExternalLink, Globe2, KeyRound, Loader2, Palette, Save, Share2 } from "lucide-react";
import { API_URL, api, getSessionUser } from "@/lib/api";

type Domain={id:number;hostname:string;status:string;verification_token:string;verified_at?:string|null};
type TenantProfile={id:number;name:string;slug:string;facebook_page_name?:string|null;facebook_page_id?:string|null;logo_url?:string|null;accent_color:string;generated_url:string;domains:Domain[]};
type MetaStatus={app_id?:string|null;app_secret_configured:boolean;page_id?:string|null;page_access_token_configured:boolean;graph_api_version:string;connected:boolean;page_name?:string|null};

export default function TenantSettings(){
  const router=useRouter(); const [profile,setProfile]=useState<TenantProfile|null>(null); const [meta,setMeta]=useState<MetaStatus|null>(null);
  const [form,setForm]=useState({name:"",facebook_page_name:"",facebook_page_id:"",logo_url:"",accent_color:"#e31545"});
  const [metaForm,setMetaForm]=useState({app_id:"",app_secret:"",page_id:"",page_access_token:"",graph_api_version:"v24.0"});
  const [domain,setDomain]=useState(""); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState("");

  async function load(){
    const [p,m]=await Promise.all([api<TenantProfile>("/api/v1/tenant-admin/profile",{},true),api<MetaStatus>("/api/v1/tenant-admin/meta",{},true)]);
    setProfile(p); setMeta(m);
    setForm({name:p.name,facebook_page_name:p.facebook_page_name||"",facebook_page_id:p.facebook_page_id||"",logo_url:p.logo_url||"",accent_color:p.accent_color||"#e31545"});
    setMetaForm(v=>({...v,app_id:m.app_id||"",page_id:m.page_id||"",graph_api_version:m.graph_api_version||"v24.0"}));
  }
  useEffect(()=>{const u=getSessionUser();if(!u?.is_tenant_admin){router.replace("/advertiser");return;}load().catch(e=>setError(e.message));},[router]);

  async function saveProfile(e:FormEvent){e.preventDefault();setBusy("profile");setError("");setMessage("");try{const p=await api<TenantProfile>("/api/v1/tenant-admin/profile",{method:"PUT",body:JSON.stringify({...form,facebook_page_name:form.facebook_page_name||null,facebook_page_id:form.facebook_page_id||null,logo_url:form.logo_url||null})},true);setProfile(v=>v?{...v,...p}:p);setMessage("Portal identity saved.");}catch(e){setError(e instanceof Error?e.message:"Unable to save portal")}finally{setBusy("")}}
  async function saveMeta(e:FormEvent){e.preventDefault();setBusy("meta");setError("");setMessage("");try{const payload={app_id:metaForm.app_id||null,page_id:metaForm.page_id||null,graph_api_version:metaForm.graph_api_version,...(metaForm.app_secret?{app_secret:metaForm.app_secret}:{}),...(metaForm.page_access_token?{page_access_token:metaForm.page_access_token}:{})};const m=await api<MetaStatus>("/api/v1/tenant-admin/meta",{method:"PUT",body:JSON.stringify(payload)},true);setMeta(m);setMetaForm(v=>({...v,app_secret:"",page_access_token:""}));setMessage("Facebook Page credentials saved securely.");}catch(e){setError(e instanceof Error?e.message:"Unable to save Meta settings")}finally{setBusy("")}}
  async function testMeta(){setBusy("test");setError("");setMessage("");try{const m=await api<{connected:boolean;page_name:string}>("/api/v1/tenant-admin/meta/test",{method:"POST"},true);setMessage("Connected to "+m.page_name+".");await load();}catch(e){setError(e instanceof Error?e.message:"Meta connection test failed")}finally{setBusy("")}}
  async function addDomain(e:FormEvent){e.preventDefault();setBusy("domain");setError("");setMessage("");try{const d=await api<any>("/api/v1/tenant-admin/domains",{method:"POST",body:JSON.stringify({hostname:domain})},true);setDomain("");setMessage("Custom domain added. Add the DNS records shown below, then request platform verification.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to add domain")}finally{setBusy("")}}
  async function copy(value:string){await navigator.clipboard.writeText(value);setMessage("Copied.");}

  if(!profile)return <main className="grid min-h-screen place-items-center bg-[#f5f6fa]">{error?<p className="text-rose-700">{error}</p>:<Loader2 className="animate-spin text-[#e31545]"/>}</main>;
  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center gap-4 px-4 sm:px-6"><Link href="/advertiser" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Page Portal Settings</h1><p className="text-xs text-slate-500">Branding, Facebook connection, generated URL and custom domains.</p></div><a href={profile.generated_url} target="_blank" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-extrabold text-[#070a45]">Open portal <ExternalLink size={15}/></a></div></header>
  <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">{error&&<Notice error>{error}</Notice>}{message&&<Notice>{message}</Notice>}
    <section className="rounded-[1.6rem] bg-[#070a45] p-6 text-white sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-white/45">Generated portal URL</p><div className="mt-3 flex flex-col gap-3 sm:flex-row sm:items-center"><code className="min-w-0 flex-1 break-all rounded-xl bg-white/10 px-4 py-3 text-sm">{profile.generated_url}</code><button onClick={()=>copy(profile.generated_url)} className="inline-flex items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-[#070a45]"><Copy size={15}/> Copy URL</button></div></section>
    <div className="grid gap-6 lg:grid-cols-2"><form onSubmit={saveProfile} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><Header icon={<Palette/>} title="Portal identity" text="This branding is used on the generated Page portal."/><div className="mt-5 space-y-4"><Field label="Portal / Page name" value={form.name} onChange={v=>setForm(x=>({...x,name:v}))}/><Field label="Facebook Page name" value={form.facebook_page_name} onChange={v=>setForm(x=>({...x,facebook_page_name:v}))}/><Field label="Facebook Page ID" value={form.facebook_page_id} onChange={v=>setForm(x=>({...x,facebook_page_id:v}))}/><Field label="Logo URL" value={form.logo_url} onChange={v=>setForm(x=>({...x,logo_url:v}))} placeholder="/media/logo.png or https://..."/><label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">Accent colour</span><div className="flex items-center gap-3"><input type="color" value={form.accent_color} onChange={e=>setForm(x=>({...x,accent_color:e.target.value}))} className="h-12 w-16 rounded-xl border border-slate-200 bg-white p-1"/><input value={form.accent_color} onChange={e=>setForm(x=>({...x,accent_color:e.target.value}))} className="h-12 flex-1 rounded-xl border border-slate-200 px-3 text-sm"/></div></label><button disabled={busy==="profile"} className="primary"><Save size={16}/> {busy==="profile"?"Saving...":"Save portal identity"}</button></div></form>
    <form onSubmit={saveMeta} className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><Header icon={<Share2/>} title="This Page's Meta connection" text="Credentials are stored per tenant, encrypted, and never shared with another Page."/><div className="mt-5 space-y-4"><Field label="Meta App ID" value={metaForm.app_id} onChange={v=>setMetaForm(x=>({...x,app_id:v}))}/><Secret label="Meta App Secret" value={metaForm.app_secret} onChange={v=>setMetaForm(x=>({...x,app_secret:v}))} placeholder={meta?.app_secret_configured?"Stored securely — enter to replace":"Enter app secret"}/><Field label="Facebook Page ID" value={metaForm.page_id} onChange={v=>setMetaForm(x=>({...x,page_id:v}))}/><Secret label="Page access token" value={metaForm.page_access_token} onChange={v=>setMetaForm(x=>({...x,page_access_token:v}))} placeholder={meta?.page_access_token_configured?"Stored securely — enter to replace":"Enter Page access token"}/><Field label="Graph API version" value={metaForm.graph_api_version} onChange={v=>setMetaForm(x=>({...x,graph_api_version:v}))}/><div className="flex gap-2"><button disabled={busy!==""} className="primary flex-1"><KeyRound size={16}/> Save credentials</button><button type="button" onClick={testMeta} disabled={busy!==""} className="rounded-xl border border-slate-200 px-4 text-sm font-extrabold text-[#070a45]">{busy==="test"?"Testing...":"Test"}</button></div>{meta?.connected&&<div className="flex items-center gap-2 rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700"><CheckCircle2 size={16}/> Connected{meta.page_name?" to "+meta.page_name:""}</div>}</div></form></div>
    <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><Header icon={<Globe2/>} title="Custom domains" text="Point your domain to this platform, then have the mapping verified. Only verified domains are used for tenant routing."/><form onSubmit={addDomain} className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="ads.yourdomain.com" className="h-12 rounded-xl border border-slate-200 px-4 text-sm outline-none"/><button disabled={busy==="domain"} className="rounded-xl bg-[#070a45] px-5 text-sm font-extrabold text-white">{busy==="domain"?"Adding...":"Add domain"}</button></form><div className="mt-5 divide-y divide-slate-100">{profile.domains.length===0?<p className="py-4 text-sm text-slate-500">No custom domains yet.</p>:profile.domains.map(d=><div key={d.id} className="py-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-extrabold text-[#070a45]">{d.hostname}</p><p className="mt-1 text-xs text-slate-400">TXT verification token: {d.verification_token}</p></div><span className={"rounded-full px-3 py-1 text-xs font-extrabold "+(d.status==="verified"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700")}>{d.status}</span></div><p className="mt-3 text-xs leading-5 text-slate-500">Create a CNAME from <b>{d.hostname}</b> to the platform hostname and a TXT record named <b>_meloli-verify.{d.hostname}</b> with the token above. Once verified, visiting your domain opens this portal automatically.</p></div>)}</div></section>
  </div><style jsx>{".primary{display:flex;height:3rem;width:100%;align-items:center;justify-content:center;gap:.5rem;border-radius:.75rem;background:#e31545;color:white;font-size:.8125rem;font-weight:800}"}</style></main>
}
function Header({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]">{icon}</div><div><h2 className="font-black text-[#070a45]">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-500">{text}</p></div></div>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-[#070a45]"/></label>}
function Secret({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-wider text-slate-500">{label}</span><input type="password" autoComplete="new-password" value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none focus:border-[#070a45]"/></label>}
function Notice({children,error=false}:{children:React.ReactNode;error?:boolean}){return <div className={"rounded-2xl border p-4 text-sm font-semibold "+(error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700")}>{children}</div>}
