import Link from "next/link";
import { Bell, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileText, LayoutDashboard, LogOut, Megaphone, Menu, Plus, Search, Settings, Users } from "lucide-react";

const campaigns = [
  {name:"October Store Promotion", client:"Maseru Home Centre", status:"Approved", date:"03 Oct · 10:00", amount:"M 650.00"},
  {name:"Weekend Special", client:"Mountain View Restaurant", status:"In review", date:"04 Oct · 09:00", amount:"M 450.00"},
  {name:"Graduate Recruitment", client:"Highlands Consulting", status:"Changes requested", date:"06 Oct · 12:00", amount:"M 900.00"},
  {name:"New Product Launch", client:"Naleli Cosmetics", status:"Payment pending", date:"08 Oct · 15:00", amount:"M 650.00"},
];

export default function Dashboard(){return <main className="min-h-screen bg-[#f5f6fa] text-slate-900">
  <aside className="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col border-r border-white/10 bg-[#070a45] text-white lg:flex">
    <div className="flex h-20 items-center gap-3 border-b border-white/10 px-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10"><Megaphone size={20}/></div><div><div className="font-black tracking-tight">MELOLI<span className="text-[#ff315d]">AIRWAVES</span></div><div className="text-[10px] uppercase tracking-[.2em] text-white/45">Admin Console</div></div></div>
    <nav className="flex-1 space-y-1 p-4 text-sm font-bold"><Nav icon={<LayoutDashboard/>} label="Overview" active href="/dashboard"/><Nav icon={<Megaphone/>} label="Campaigns" badge="12"/><Nav icon={<CheckCircle2/>} label="Approvals" badge="5"/><Nav icon={<CalendarDays/>} label="Publishing calendar"/><Nav icon={<Users/>} label="Advertisers"/><Nav icon={<CircleDollarSign/>} label="Payments"/><Nav icon={<FileText/>} label="Reports"/><Nav icon={<Settings/>} label="Settings" href="/dashboard/settings"/></nav>
    <div className="border-t border-white/10 p-4"><div className="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e31545] text-sm font-black">MA</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">Meloli Admin</p><p className="truncate text-xs text-white/45">Publisher account</p></div><LogOut size={17} className="text-white/40"/></div></div>
  </aside>

  <div className="lg:pl-72">
    <header className="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 lg:hidden"><Menu size={20}/></button><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-black text-[#070a45]">Advertising Operations</h1><p className="hidden text-xs text-slate-500 sm:block">Thursday, 01 October 2026</p></div><div className="hidden h-11 w-72 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-3 md:flex"><Search size={17} className="text-slate-400"/><input className="w-full bg-transparent text-sm outline-none" placeholder="Search campaigns..."/></div><button className="relative grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white"><Bell size={18}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#e31545]"/></button><button className="hidden items-center gap-2 rounded-xl bg-[#e31545] px-4 py-3 text-sm font-extrabold text-white sm:flex"><Plus size={17}/> New campaign</button></header>

    <div className="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">
      <section className="mb-6 rounded-[1.75rem] bg-[#070a45] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-6 xl:flex-row xl:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-white/50">Meloli Airwaves Media</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Good afternoon, your queue is under control.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Five campaigns need editorial attention, three are scheduled for today and all published content remains traceable from submission to posting.</p></div><div className="flex flex-wrap gap-3"><button className="rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-[#070a45]">Review approvals</button><button className="rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm font-extrabold">View calendar</button></div></div></section>

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Megaphone/>} label="Active campaigns" value="28" change="+6 this month"/><Metric icon={<Clock3/>} label="Awaiting review" value="05" change="2 submitted today"/><Metric icon={<CalendarDays/>} label="Scheduled" value="12" change="3 publishing today"/><Metric icon={<CircleDollarSign/>} label="October revenue" value="M 18,460" change="Paid adverts"/></section>

      <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]">
        <div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:p-6"><div><h3 className="font-black text-[#070a45]">Campaign queue</h3><p className="mt-1 text-sm text-slate-500">Latest submissions and publishing decisions</p></div><button className="text-sm font-extrabold text-[#e31545]">View all</button></div><div className="divide-y divide-slate-100">{campaigns.map(c=><div key={c.name} className="grid gap-3 p-5 transition hover:bg-slate-50 sm:grid-cols-[1.4fr_.9fr_.8fr_auto] sm:items-center sm:px-6"><div><p className="font-extrabold text-slate-900">{c.name}</p><p className="mt-1 text-sm text-slate-500">{c.client}</p></div><div><Status value={c.status}/></div><div><p className="text-sm font-bold text-slate-700">{c.date}</p><p className="mt-1 text-xs text-slate-400">Preferred publish time</p></div><div className="flex items-center justify-between gap-4 sm:justify-end"><span className="text-sm font-black text-[#070a45]">{c.amount}</span><ChevronRight size={17} className="text-slate-300"/></div></div>)}</div></div>

        <div className="space-y-6"><div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-black text-[#070a45]">Today&apos;s schedule</h3><p className="mt-1 text-sm text-slate-500">01 October</p></div><CalendarDays size={20} className="text-[#e31545]"/></div><div className="mt-6 space-y-5"><Schedule time="09:00" title="Back to school offers" state="Published"/><Schedule time="12:30" title="Business directory feature" state="Ready"/><Schedule time="15:00" title="Weekend accommodation" state="Scheduled"/><Schedule time="18:00" title="Restaurant special" state="Scheduled"/></div></div><div className="rounded-[1.6rem] bg-[#e31545] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-white/70">Editorial control</p><h3 className="mt-3 text-2xl font-black">Nothing publishes without approval.</h3><p className="mt-3 text-sm leading-6 text-white/75">Every action is recorded, from client submission and payment to reviewer decision and publishing status.</p></div></div>
      </section>
    </div>
  </div>
</main>}

function Nav({icon,label,badge,active,href}:{icon:React.ReactNode;label:string;badge?:string;active?:boolean;href?:string}){const cls=`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left ${active?"bg-white text-[#070a45]":"text-white/65 hover:bg-white/5 hover:text-white"}`; const content=<><span className="[&>svg]:h-[18px] [&>svg]:w-[18px]">{icon}</span><span className="flex-1">{label}</span>{badge&&<span className={`rounded-full px-2 py-0.5 text-xs ${active?"bg-[#e31545] text-white":"bg-white/10"}`}>{badge}</span>}</>; return href?<Link href={href} className={cls}>{content}</Link>:<button className={cls}>{content}</button>}
function Metric({icon,label,value,change}:{icon:React.ReactNode;label:string;value:string;change:string}){return <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="flex items-start justify-between"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><span className="text-xs font-bold text-slate-400">Live</span></div><p className="mt-5 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black tracking-tight text-[#070a45]">{value}</p><p className="mt-2 text-xs font-semibold text-slate-400">{change}</p></div>}
function Status({value}:{value:string}){const styles=value==="Approved"?"bg-emerald-50 text-emerald-700":value==="In review"?"bg-amber-50 text-amber-700":value==="Changes requested"?"bg-rose-50 text-rose-700":"bg-slate-100 text-slate-600";return <span className={`inline-flex rounded-full px-3 py-1.5 text-xs font-extrabold ${styles}`}>{value}</span>}
function Schedule({time,title,state}:{time:string;title:string;state:string}){return <div className="flex gap-4"><div className="w-12 pt-0.5 text-xs font-black text-[#070a45]">{time}</div><div className="relative flex-1 border-l border-slate-200 pl-4 before:absolute before:-left-[5px] before:top-1 before:h-2.5 before:w-2.5 before:rounded-full before:bg-[#e31545]"><p className="text-sm font-extrabold text-slate-800">{title}</p><p className="mt-1 text-xs text-slate-400">{state}</p></div></div>}
