"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { BadgePercent, Bell, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileText, Globe2, Headphones, KeyRound, LayoutDashboard, Loader2, LogOut, Megaphone, Menu, Package, Send, Search, Settings, ShieldCheck, TrendingUp, Users } from "lucide-react";
import { api, clearSession, getSessionUser, SessionUser } from "@/lib/api";

type Campaign={id:number;advertiser_id:number;title:string;status:string;preferred_publish_at?:string|null;scheduled_publish_at?:string|null;created_at:string};
type Summary={advertisers:number;campaigns:number;awaiting_review:number;scheduled:number;published:number;paid_payments:number;revenue:number;currency:string;failed_publications:number};

const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());

export default function Dashboard(){
  const router=useRouter();
  const [user,setUser]=useState<SessionUser|null>(null);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [summary,setSummary]=useState<Summary|null>(null);
  const [loading,setLoading]=useState(true);
  const [query,setQuery]=useState("");
  const [error,setError]=useState("");
  const [portalName,setPortalName]=useState("Meloli Airwaves");

  useEffect(()=>{const current=getSessionUser();if(!current||(current.role==="advertiser"&&!current.is_tenant_admin)){router.replace("/login");return;}setUser(current);const base=Promise.all([api<Campaign[]>("/api/v1/campaigns",{},true),api<Summary>("/api/v1/admin/reports/summary",{},true)]).then(([c,s])=>{setCampaigns(c);setSummary(s)});const brand=current.is_tenant_admin?api<{name:string}>("/api/v1/tenant-admin/profile",{},true).then(p=>setPortalName(p.name)).catch(()=>undefined):Promise.resolve();Promise.all([base,brand]).catch(e=>setError(e instanceof Error?e.message:"Unable to load dashboard")).finally(()=>setLoading(false));},[router]);
  const filtered=useMemo(()=>campaigns.filter(c=>c.title.toLowerCase().includes(query.toLowerCase())).slice(0,8),[campaigns,query]);
  const schedule=useMemo(()=>campaigns.filter(c=>c.scheduled_publish_at&&["scheduled","published"].includes(c.status)).sort((a,b)=>new Date(a.scheduled_publish_at!).getTime()-new Date(b.scheduled_publish_at!).getTime()).slice(0,5),[campaigns]);
  const kpis=useMemo(()=>{
    const total=summary?.campaigns||0;
    const published=summary?.published||0;
    const awaiting=summary?.awaiting_review||0;
    const advertisers=summary?.advertisers||0;
    const failed=summary?.failed_publications||0;
    const approved=campaigns.filter(c=>["approved","scheduled","published"].includes(c.status)).length;
    const publishRate=total?Math.round((published/total)*100):0;
    const approvalRate=total?Math.round((approved/total)*100):0;
    const backlogRate=total?Math.round((awaiting/total)*100):0;
    const failureRate=(published+failed)?Math.round((failed/(published+failed))*100):0;
    const revenuePerAdvertiser=advertisers?Number(summary?.revenue||0)/advertisers:0;
    return {approved,publishRate,approvalRate,backlogRate,failureRate,revenuePerAdvertiser};
  },[campaigns,summary]);
  function logout(){clearSession();router.push("/login")}

  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900">
    <aside className="fixed inset-y-0 left-0 z-40 hidden w-72 flex-col border-r border-white/10 bg-[#070a45] text-white lg:flex"><div className="flex h-20 items-center gap-3 border-b border-white/10 px-6"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-white/10"><Megaphone size={20}/></div><div><div className="font-black tracking-tight">{portalName}</div><div className="text-[10px] uppercase tracking-[.2em] text-white/45">Admin Console</div></div></div><nav className="flex-1 space-y-1 overflow-y-auto p-4 text-sm font-bold"><Nav icon={<LayoutDashboard/>} label="Overview" active href="/dashboard"/><Nav icon={<Megaphone/>} label="Campaigns" href="/dashboard/campaigns"/><Nav icon={<CheckCircle2/>} label="Approvals" href="/dashboard/campaigns"/><Nav icon={<CalendarDays/>} label="Publishing calendar" href="/dashboard/calendar"/><Nav icon={<Package/>} label="Packages & pricing" href="/dashboard/packages"/>{user?.role==="super_admin"&&<Nav icon={<BadgePercent/>} label="Commercial growth" href="/dashboard/commercial"/>}{user?.role==="super_admin"&&<Nav icon={<TrendingUp/>} label="Growth & referrals" href="/dashboard/growth"/>}{user?.role==="super_admin"&&<Nav icon={<KeyRound/>} label="Corporate API" href="/dashboard/corporate-api"/>}{user?.role==="super_admin"&&<Nav icon={<Globe2/>} label="Page portals" href="/dashboard/tenants"/>}<Nav icon={<Users/>} label="Advertisers" href="/dashboard/campaigns"/><Nav icon={<CircleDollarSign/>} label="Payments" href="/dashboard/payments"/>{user?.role==="super_admin"&&<Nav icon={<FileText/>} label="Refund review" href="/dashboard/refunds"/>}<Nav icon={<FileText/>} label="Reports" href="/dashboard/reports"/><Nav icon={<Headphones/>} label="Advertiser support" href="/dashboard/support"/>{user?.role==="super_admin"&&<Nav icon={<Bell/>} label="Notification delivery" href="/dashboard/notification-delivery"/>}<Nav icon={<ShieldCheck/>} label="Staff security" href="/dashboard/security"/>{user?.role==="super_admin"&&<Nav icon={<FileText/>} label="Audit & activity" href="/dashboard/audit"/>}{user?.role==="super_admin"&&<Nav icon={<Send/>} label="Notifications" href="/dashboard/communications"/>}{user?.is_tenant_admin&&<><Nav icon={<Users/>} label="Page team & onboarding" href="/tenant-admin/team"/><Nav icon={<Globe2/>} label="Page portal settings" href="/tenant-admin/settings"/></>}{!user?.is_tenant_admin&&<Nav icon={<Settings/>} label="Settings" href="/dashboard/settings"/>}</nav><button onClick={logout} className="m-4 flex items-center gap-3 rounded-2xl bg-white/5 p-3 text-left"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e31545] text-sm font-black">{user?.full_name?.slice(0,2).toUpperCase()||"MA"}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{user?.full_name||"Meloli Admin"}</p><p className="truncate text-xs text-white/45">{user?.role?.replaceAll("_"," ")||"staff"}</p></div><LogOut size={17} className="text-white/40"/></button></aside>

    <div className="lg:pl-72"><header className="sticky top-0 z-30 flex h-20 items-center gap-4 border-b border-slate-200/80 bg-white/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><button className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 lg:hidden"><Menu size={20}/></button><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-black text-[#070a45]">Advertising Operations</h1><p className="hidden text-xs text-slate-500 sm:block">Live {portalName} advertising workflow</p></div><div className="hidden h-11 w-72 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-3 md:flex"><Search size={17} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search campaigns..."/></div><Link href="/dashboard/reports" className="relative grid h-11 w-11 place-items-center rounded-xl border border-slate-200 bg-white"><Bell size={18}/>{summary?.failed_publications?<span className="absolute right-2 top-2 h-2 w-2 rounded-full bg-[#e31545]"/>:null}</Link></header>

      <div className="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}<section className="mb-6 rounded-[1.75rem] bg-[#070a45] p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-6 xl:flex-row xl:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-white/50">{portalName}</p><h2 className="mt-2 text-3xl font-black tracking-tight sm:text-4xl">Advertising operations at a glance.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Track revenue, advertiser growth, editorial workload and publishing health from live system data.</p></div><div className="flex flex-wrap gap-3"><Link href="/dashboard/campaigns" className="rounded-xl bg-white px-4 py-3 text-sm font-extrabold text-[#070a45]">Review approvals</Link><Link href="/dashboard/reports" className="rounded-xl border border-white/15 bg-white/5 px-4 py-3 text-sm font-extrabold">Detailed reports</Link></div></div></section>

        {loading?<div className="grid min-h-48 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<><section><div className="mb-3 flex items-end justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#e31545]">{portalName} KPIs</p><h3 className="mt-1 text-xl font-black text-[#070a45]">Commercial & operational performance</h3></div><span className="hidden text-xs font-bold text-slate-400 sm:block">Live platform indicators</span></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CircleDollarSign/>} label="Confirmed revenue" value={`${summary?.currency||"LSL"} ${Number(summary?.revenue||0).toLocaleString()}`} change={`${summary?.paid_payments||0} paid transactions`}/><Metric icon={<Users/>} label="Advertisers" value={String(summary?.advertisers||0)} change={`${summary?.currency||"LSL"} ${kpis.revenuePerAdvertiser.toLocaleString(undefined,{maximumFractionDigits:0})} avg. revenue / advertiser`}/><Metric icon={<CheckCircle2/>} label="Approval rate" value={`${kpis.approvalRate}%`} change={`${kpis.approved} approved, scheduled or published`}/><Metric icon={<TrendingUp/>} label="Publish rate" value={`${kpis.publishRate}%`} change={`${summary?.published||0} of ${summary?.campaigns||0} campaigns published`}/><Metric icon={<Clock3/>} label="Editorial backlog" value={String(summary?.awaiting_review||0)} change={`${kpis.backlogRate}% of total campaign volume`}/><Metric icon={<CalendarDays/>} label="Scheduled" value={String(summary?.scheduled||0)} change="Upcoming approved publications"/><Metric icon={<Megaphone/>} label="Total campaigns" value={String(summary?.campaigns||0)} change="All advertiser submissions"/><Metric icon={<Bell/>} label="Publish failure rate" value={`${kpis.failureRate}%`} change={`${summary?.failed_publications||0} failed Meta attempts`}/></div></section>

          <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-100 p-5 sm:p-6"><div><h3 className="font-black text-[#070a45]">Campaign queue</h3><p className="mt-1 text-sm text-slate-500">Latest submissions and publishing decisions</p></div><Link href="/dashboard/campaigns" className="text-sm font-extrabold text-[#e31545]">View all</Link></div>{filtered.length===0?<div className="p-8 text-sm text-slate-500">No campaigns match your search.</div>:<div className="divide-y divide-slate-100">{filtered.map(c=><Link href="/dashboard/campaigns" key={c.id} className="grid gap-3 p-5 transition hover:bg-slate-50 sm:grid-cols-[1fr_.7fr_auto] sm:items-center sm:px-6"><div><p className="font-extrabold text-slate-900">{c.title}</p><p className="mt-1 text-xs text-slate-400">Advertiser #{c.advertiser_id} · Campaign #{c.id}</p></div><Status value={c.status}/><ChevronRight size={17} className="text-slate-300"/></Link>)}</div>}</div>
            <div className="space-y-6"><div className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-black text-[#070a45]">Publishing schedule</h3><p className="mt-1 text-sm text-slate-500">Next scheduled campaigns</p></div><CalendarDays size={20} className="text-[#e31545]"/></div><div className="mt-6 space-y-5">{schedule.length===0?<p className="text-sm text-slate-500">Nothing scheduled yet.</p>:schedule.map(c=><Schedule key={c.id} date={c.scheduled_publish_at!} title={c.title} state={label(c.status)}/>)}</div></div><div className="rounded-[1.6rem] bg-[#e31545] p-6 text-white"><p className="text-xs font-black uppercase tracking-[.18em] text-white/70">Publishing health</p><h3 className="mt-3 text-2xl font-black">{summary?.failed_publications||0} failed attempts</h3><p className="mt-3 text-sm leading-6 text-white/75">Current failed-attempt rate is {kpis.failureRate}%. Open Reports to inspect failures and retry after configuration or content issues are corrected.</p><Link href="/dashboard/reports" className="mt-4 inline-flex rounded-xl bg-white px-4 py-2.5 text-sm font-black text-[#e31545]">Open reports</Link></div></div></section></>}
      </div></div>
  </main>;
}

function Nav({icon,label,active,href}:{icon:React.ReactNode;label:string;active?:boolean;href:string}){return <Link href={href} className={`flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left ${active?"bg-white text-[#070a45]":"text-white/65 hover:bg-white/5 hover:text-white"}`}><span className="[&>svg]:h-[18px] [&>svg]:w-[18px]">{icon}</span><span className="flex-1">{label}</span></Link>}
function Metric({icon,label,value,change}:{icon:React.ReactNode;label:string;value:string;change:string}){return <div className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><p className="mt-5 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 break-words text-3xl font-black tracking-tight text-[#070a45]">{value}</p><p className="mt-2 text-xs font-semibold leading-5 text-slate-400">{change}</p></div>}
function Status({value}:{value:string}){const cls=value==="published"?"bg-emerald-50 text-emerald-700":value==="approved"||value==="scheduled"?"bg-blue-50 text-blue-700":value==="rejected"||value==="changes_requested"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700";return <span className={`w-fit rounded-full px-3 py-1.5 text-xs font-extrabold ${cls}`}>{label(value)}</span>}
function Schedule({date,title,state}:{date:string;title:string;state:string}){const d=new Date(date);return <div className="flex gap-4"><div className="w-14 pt-0.5 text-xs font-black text-[#070a45]">{d.toLocaleDateString(undefined,{month:"short",day:"numeric"})}<br/><span className="text-slate-400">{d.toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})}</span></div><div className="relative flex-1 border-l border-slate-200 pl-4 before:absolute before:-left-[5px] before:top-1 before:h-2.5 before:w-2.5 before:rounded-full before:bg-[#e31545]"><p className="text-sm font-extrabold text-slate-800">{title}</p><p className="mt-1 text-xs text-slate-400">{state}</p></div></div>}
