"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, BadgeCheck, CircleDollarSign, Clock3, Eye, Loader2, Megaphone, MousePointerClick, RefreshCw, Send, Share2, ThumbsUp, TrendingUp, Users } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Summary={advertisers:number;campaigns:number;awaiting_review:number;scheduled:number;published:number;paid_payments:number;revenue:number;currency:string;failed_publications:number};
type Performance={campaigns_published:number;campaigns_with_metrics:number;impressions:number;reach:number;engaged_users:number;clicks:number;reactions:number;comments:number;shares:number;video_views:number;engagement_rate:number;click_rate:number};
type Publication={id:number;campaign_id:number;status:string;attempt_number:number;external_post_id?:string|null;external_post_url?:string|null;error_message?:string|null;created_at:string};
type BulkSync={eligible:number;synced:number;failed:number;failures:string[]};

export default function ReportsPage(){
  const router=useRouter();
  const [summary,setSummary]=useState<Summary|null>(null);
  const [performance,setPerformance]=useState<Performance|null>(null);
  const [publications,setPublications]=useState<Publication[]>([]);
  const [loading,setLoading]=useState(true);
  const [syncing,setSyncing]=useState(false);
  const [canSync,setCanSync]=useState(false);
  const [syncMessage,setSyncMessage]=useState("");
  const [error,setError]=useState("");

  async function load(){setLoading(true);setError("");try{const [s,p,perf]=await Promise.all([api<Summary>("/api/v1/admin/reports/summary",{},true),api<Publication[]>("/api/v1/publications",{},true),api<Performance>("/api/v1/admin/performance/summary",{},true)]);setSummary(s);setPublications(p);setPerformance(perf);}catch(e){setError(e instanceof Error?e.message:"Unable to load reports");}finally{setLoading(false)}}
  useEffect(()=>{const user=getSessionUser();if(!user||user.role==="advertiser"){router.replace("/login");return;}setCanSync(["publisher","super_admin"].includes(user.role));load();},[router]);
  async function syncPerformance(){setSyncing(true);setError("");setSyncMessage("");try{const result=await api<BulkSync>("/api/v1/admin/performance/sync",{method:"POST"},true);setSyncMessage(`Facebook KPIs refreshed for ${result.synced} of ${result.eligible} eligible campaigns${result.failed?`; ${result.failed} failed`:""}.`);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to sync Facebook KPIs");}finally{setSyncing(false)}}

  return <main className="min-h-screen bg-[#f0f2f5] text-slate-900">
    <header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6 lg:px-8"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="min-w-0 flex-1"><h1 className="font-bold text-slate-900">Advertising Reports</h1><p className="hidden text-xs text-slate-500 sm:block">Revenue, operations and campaign performance from live Meloli advertising data.</p></div>{canSync&&<button disabled={syncing} onClick={syncPerformance} className="hidden items-center gap-2 rounded-xl bg-[#070a45] px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50 sm:flex">{syncing?<Loader2 size={16} className="animate-spin"/>:<RefreshCw size={16}/>} Sync Facebook KPIs</button>}<button onClick={load} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-900"><RefreshCw size={16}/> Refresh</button></div></header>
    <div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">
      {syncMessage&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{syncMessage}</div>}
      {loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-[#0866ff]"/></div>:error?<div className="rounded-xl border border-rose-200 bg-rose-50 p-5 text-sm font-semibold text-rose-700">{error}</div>:summary&&<>
        <section><p className="text-xs font-bold tracking-normal text-[#0866ff]">Business KPIs</p><div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<CircleDollarSign/>} label="Confirmed revenue" value={`${summary.currency} ${Number(summary.revenue).toLocaleString(undefined,{minimumFractionDigits:2})}`}/><Metric icon={<Megaphone/>} label="Campaigns" value={String(summary.campaigns)}/><Metric icon={<Users/>} label="Advertisers" value={String(summary.advertisers)}/><Metric icon={<BadgeCheck/>} label="Published" value={String(summary.published)}/><Metric icon={<Clock3/>} label="Awaiting review" value={String(summary.awaiting_review)}/><Metric icon={<Send/>} label="Scheduled" value={String(summary.scheduled)}/><Metric icon={<CircleDollarSign/>} label="Paid transactions" value={String(summary.paid_payments)}/><Metric icon={<RefreshCw/>} label="Failed publish attempts" value={String(summary.failed_publications)}/></div></section>
        {performance&&<section className="mt-8"><div className="flex flex-col justify-between gap-2 sm:flex-row sm:items-end"><div><p className="text-xs font-bold tracking-normal text-[#0866ff]">Audience performance</p><h2 className="mt-1 text-xl font-bold text-slate-900">Facebook campaign KPIs</h2><p className="mt-1 text-sm text-slate-500">Synced post performance for published Meloli adverts.</p></div><p className="text-xs font-bold text-slate-400">{performance.campaigns_with_metrics} of {performance.campaigns_published} published campaigns have synced metrics</p></div><div className="mt-3 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Eye/>} label="Impressions" value={performance.impressions.toLocaleString()}/><Metric icon={<Users/>} label="Reach" value={performance.reach.toLocaleString()}/><Metric icon={<TrendingUp/>} label="Engagement rate" value={`${performance.engagement_rate}%`}/><Metric icon={<MousePointerClick/>} label="Click rate" value={`${performance.click_rate}%`}/><Metric icon={<MousePointerClick/>} label="Clicks" value={performance.clicks.toLocaleString()}/><Metric icon={<ThumbsUp/>} label="Reactions" value={performance.reactions.toLocaleString()}/><Metric icon={<Share2/>} label="Shares" value={performance.shares.toLocaleString()}/><Metric icon={<Megaphone/>} label="Engaged users" value={performance.engaged_users.toLocaleString()}/></div></section>}
        <section className="mt-8 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-bold text-slate-900">Facebook publishing history</h2><p className="mt-1 text-sm text-slate-500">Most recent attempts, including failures that may need a retry.</p></div>{publications.length===0?<div className="p-8 text-sm text-slate-500">No publication attempts yet.</div>:<div className="divide-y divide-slate-100">{publications.slice(0,50).map(p=><div key={p.id} className="grid gap-3 p-5 sm:grid-cols-[100px_1fr_auto] sm:items-center"><div className="text-xs font-bold text-slate-400">Campaign #{p.campaign_id}</div><div><div className="flex items-center gap-2"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${p.status==="published"?"bg-emerald-50 text-emerald-700":p.status==="failed"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700"}`}>{p.status}</span><span className="text-xs text-slate-400">Attempt {p.attempt_number}</span></div><p className="mt-2 text-sm text-slate-500">{p.error_message||p.external_post_id||"Publishing request prepared"}</p></div><div className="text-right">{p.external_post_url?<a href={p.external_post_url} target="_blank" className="text-sm font-semibold text-[#0866ff]">Open post ↗</a>:<span className="text-xs text-slate-400">{new Date(p.created_at).toLocaleString()}</span>}</div></div>)}</div>}</section>
      </>}
    </div>
  </main>;
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-[1.45rem] border border-slate-200 bg-white p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f3ff] text-slate-900 [&>svg]:h-5 [&>svg]:w-5">{icon}</div><p className="mt-4 text-xs font-bold tracking-normal text-slate-400">{label}</p><p className="mt-1 break-words text-2xl font-bold text-slate-900">{value}</p></div>}
