"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, FileClock, Loader2, RefreshCw, Search, ShieldCheck } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Audit={id:number;actor_user_id?:number|null;actor?:string|null;action:string;entity_type:string;entity_id?:string|null;detail?:string|null;created_at:string};

export default function AuditPage(){
 const router=useRouter(); const [rows,setRows]=useState<Audit[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(""); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setRows(await api<Audit[]>("/api/v1/admin/audit?limit=500",{},true));}catch(e){setError(e instanceof Error?e.message:"Unable to load audit log")}finally{setLoading(false)}}
 useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="super_admin"){router.replace("/dashboard");return;}load();},[router]);
 const filtered=useMemo(()=>{const q=query.toLowerCase();return rows.filter(r=>[r.action,r.entity_type,r.entity_id||"",r.detail||"",r.actor||""].join(" ").toLowerCase().includes(q));},[rows,query]);
 const security=rows.filter(r=>/password|session|2fa|login/i.test(r.action)).length;
 const commercial=rows.filter(r=>/payment|refund|invoice|settled|promo|subscription|corporate/i.test(r.action)).length;
 return <main className="min-h-screen bg-[#f0f2f5] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-[1450px] items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-bold text-slate-900">Audit & Activity</h1><p className="text-xs text-slate-500">Trace sensitive administrative, commercial and security actions.</p></div><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><RefreshCw size={17}/></button></div></header><div className="mx-auto max-w-[1450px] p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}<div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric icon={<FileClock/>} label="Recent events" value={rows.length}/><Metric icon={<ShieldCheck/>} label="Security events" value={security}/><Metric icon={<FileClock/>} label="Commercial events" value={commercial}/></div><section className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><div className="flex h-12 items-center gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4"><Search size={17} className="text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent text-sm outline-none" placeholder="Search action, user, entity or detail..."/></div></div>{loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-[#0866ff]"/></div>:filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">No matching audit events.</div>:<div className="divide-y divide-slate-100">{filtered.map(r=><div key={r.id} className="grid gap-3 p-5 md:grid-cols-[1fr_.7fr_.8fr_.9fr] md:items-center"><div><p className="font-semibold text-slate-900">{r.action.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-400">{new Date(r.created_at).toLocaleString()}</p></div><div><p className="text-[10px] font-bold tracking-normal text-slate-400">Actor</p><p className="mt-1 text-sm font-bold text-slate-700">{r.actor||"System"}{r.actor_user_id?" · #"+r.actor_user_id:""}</p></div><div><p className="text-[10px] font-bold tracking-normal text-slate-400">Entity</p><p className="mt-1 text-sm font-bold text-slate-700">{r.entity_type}{r.entity_id?" #"+r.entity_id:""}</p></div><div><p className="text-[10px] font-bold tracking-normal text-slate-400">Detail</p><p className="mt-1 text-sm text-slate-600">{r.detail||"—"}</p></div></div>)}</div>}</section></div></main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f3ff] text-slate-900">{icon}</div><p className="mt-4 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold text-slate-900">{value}</p></div>}
