"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, CircleDollarSign, Loader2, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { api, getSessionUser, SessionUser } from "@/lib/api";

type Advertiser={id:number;full_name:string;business_name?:string|null;email:string;phone?:string|null;is_active:boolean;created_at:string;campaigns:number;published:number;confirmed_spend:number;currency:string};
type Staff={id:number;full_name:string;email:string;role:string;is_active:boolean;created_at:string};
type Audit={id:number;actor?:string|null;action:string;entity_type:string;entity_id?:string|null;detail?:string|null;created_at:string};
type Health={status:string;database:string;media_total_bytes:number;media_free_bytes:number;failed_publication_attempts:number;due_scheduled_campaigns:number;last_published_at?:string|null;worker_expected:boolean;backup_last_success?:string|null;backup_age_hours?:number|null;backup_max_age_hours:number;backup_stale:boolean;latest_db_backup?:string|null;latest_db_backup_bytes:number;latest_media_backup?:string|null;latest_media_backup_bytes:number;checked_at:string};
type SlaRow={campaign_id:number;title:string;advertiser_id:number;advertiser:string;kind:string;status:string;proof_status:string;age_hours:number;due_at?:string|null};
type SlaSummary={review_sla_hours:number;proof_response_target_hours:number;review_overdue:number;proof_waiting:number;publish_overdue:number;failed_notifications:number;total_attention:number;rows:SlaRow[];checked_at:string};
type ReadinessCheck={key:string;label:string;ok:boolean;detail:string;severity:string};
type Readiness={ready:boolean;critical_failures:number;warnings:number;checks:ReadinessCheck[];checked_at:string};

export default function OperationsPage(){
  const router=useRouter();
  const [user,setUser]=useState<SessionUser|null>(null);
  const [advertisers,setAdvertisers]=useState<Advertiser[]>([]);
  const [staffRows,setStaffRows]=useState<Staff[]>([]);
  const [auditRows,setAuditRows]=useState<Audit[]>([]);
  const [health,setHealth]=useState<Health|null>(null);
  const [sla,setSla]=useState<SlaSummary|null>(null);
  const [readiness,setReadiness]=useState<Readiness|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [message,setMessage]=useState("");
  const [staffForm,setStaffForm]=useState({full_name:"",email:"",password:"",role:"reviewer"});

  async function load(current?:SessionUser){const u=current||user;if(!u)return;setLoading(true);setError("");try{const [a,h,sl]=await Promise.all([api<Advertiser[]>("/api/v1/admin/advertisers",{},true),api<Health>("/api/v1/admin/system-health",{},true),api<SlaSummary>("/api/v1/admin/sla-summary",{},true)]);setAdvertisers(a);setHealth(h);setSla(sl);if(u.role==="super_admin"){const [s,l,r]=await Promise.all([api<Staff[]>("/api/v1/admin/staff",{},true),api<Audit[]>("/api/v1/admin/audit?limit=100",{},true),api<Readiness>("/api/v1/admin/production-readiness",{},true)]);setStaffRows(s);setAuditRows(l);setReadiness(r);}}catch(e){setError(e instanceof Error?e.message:"Unable to load operations");}finally{setLoading(false)}}
  useEffect(()=>{const current=getSessionUser();if(!current||current.role==="advertiser"){router.replace("/login");return;}setUser(current);load(current);},[router]);

  const totals=useMemo(()=>({spend:advertisers.reduce((s,a)=>s+Number(a.confirmed_spend||0),0),campaigns:advertisers.reduce((s,a)=>s+a.campaigns,0),published:advertisers.reduce((s,a)=>s+a.published,0)}),[advertisers]);

  async function createStaff(e:FormEvent){e.preventDefault();setError("");setMessage("");try{await api("/api/v1/admin/staff",{method:"POST",body:JSON.stringify(staffForm)},true);setMessage("Staff account created.");setStaffForm({full_name:"",email:"",password:"",role:"reviewer"});await load();}catch(err){setError(err instanceof Error?err.message:"Unable to create staff account")}}
  async function toggleUser(id:number,is_active:boolean){setError("");try{await api(`/api/v1/admin/users/${id}/state`,{method:"PATCH",body:JSON.stringify({is_active:!is_active})},true);await load();}catch(err){setError(err instanceof Error?err.message:"Unable to update account")}}

  return <main className="min-h-screen bg-[#f0f2f5] text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6 lg:px-8"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="min-w-0 flex-1"><h1 className="font-bold text-slate-900">Operations Control Centre</h1><p className="hidden text-xs text-slate-500 sm:block">Advertisers, staff, system health and audit activity.</p></div><button onClick={()=>load()} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-900"><RefreshCw size={16}/> Refresh</button></div></header>
  <div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#0866ff]"/></div>:<>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric icon={<Users/>} label="Advertisers" value={String(advertisers.length)}/><Metric icon={<CircleDollarSign/>} label="Client spend" value={`LSL ${totals.spend.toLocaleString()}`}/><Metric icon={<Activity/>} label="Campaigns" value={String(totals.campaigns)}/><Metric icon={<ShieldCheck/>} label="Worker health" value={health?.worker_expected&&health.database==="ok"?"Ready":"Check"}/><Metric icon={<Activity/>} label="Needs attention" value={String(sla?.total_attention||0)}/></section>
    <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-bold tracking-normal text-[#0866ff]">Service levels</p><h2 className="mt-1 font-bold text-slate-900">Campaign attention queue</h2><p className="mt-1 text-sm text-slate-500">Review target {sla?.review_sla_hours||4}h · advertiser proof follow-up target {sla?.proof_response_target_hours||24}h.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><MiniSla label="Review overdue" value={sla?.review_overdue||0}/><MiniSla label="Proof waiting" value={sla?.proof_waiting||0}/><MiniSla label="Publish overdue" value={sla?.publish_overdue||0}/><MiniSla label="Delivery failed" value={sla?.failed_notifications||0}/></div></div></div>{!sla||sla.rows.length===0?<div className="p-8 text-center text-sm text-slate-500">No campaign SLA exceptions right now.</div>:<div className="divide-y divide-slate-100">{sla.rows.map(row=><Link key={row.kind+"-"+row.campaign_id} href="/dashboard/campaigns" className="grid gap-3 p-5 hover:bg-slate-50 sm:grid-cols-[1fr_.8fr_.6fr_auto] sm:items-center"><div><p className="font-semibold text-slate-900">{row.title}</p><p className="mt-1 text-xs text-slate-400">Campaign #{row.campaign_id} · {row.advertiser}</p></div><p className="text-sm font-bold text-slate-600">{row.kind.replaceAll("_"," ")}</p><p className="text-sm font-bold text-[#0866ff]">{row.age_hours.toFixed(1)}h</p><span className="rounded-full bg-amber-50 px-3 py-1.5 text-xs font-semibold text-amber-700">Needs attention</span></Link>)}</div>}</section>
    {user?.role==="super_admin"&&readiness&&<section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className={"p-5 sm:p-6 "+(readiness.ready?"bg-emerald-50":"bg-rose-50")}><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold tracking-normal text-slate-500">Production readiness</p><h2 className={"mt-1 text-xl font-bold "+(readiness.ready?"text-emerald-800":"text-rose-800")}>{readiness.ready?"Critical production checks passed":"Production blockers detected"}</h2><p className="mt-1 text-sm text-slate-600">{readiness.critical_failures} critical failure(s) · {readiness.warnings} warning(s)</p></div><span className={"w-fit rounded-full px-3 py-1.5 text-xs font-semibold "+(readiness.ready?"bg-emerald-200 text-emerald-900":"bg-rose-200 text-rose-900")}>{readiness.ready?"Ready":"Not ready"}</span></div></div><div className="grid gap-3 p-5 sm:grid-cols-2 lg:grid-cols-3 sm:p-6">{readiness.checks.map(check=><div key={check.key} className={"rounded-xl border p-4 "+(check.ok?"border-emerald-200 bg-emerald-50":"border-rose-200 bg-rose-50")}><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-slate-900">{check.label}</p><span className={"rounded-full px-2 py-1 text-[10px] font-semibold "+(check.ok?"bg-emerald-200 text-emerald-800":"bg-rose-200 text-rose-800")}>{check.ok?"PASS":check.severity==="warning"?"WARN":"FAIL"}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{check.detail}</p></div>)}</div></section>}
    <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-bold text-slate-900">Advertiser accounts</h2><p className="mt-1 text-sm text-slate-500">Commercial activity and account status.</p></div><div className="divide-y divide-slate-100">{advertisers.map(a=><div key={a.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.5fr_.5fr_auto] sm:items-center"><div><p className="font-semibold">{a.business_name||a.full_name}</p><p className="mt-1 text-xs text-slate-400">{a.email} · {a.campaigns} campaigns · {a.published} published</p></div><p className="font-bold text-slate-900">{a.currency} {Number(a.confirmed_spend).toLocaleString()}</p><span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-semibold ${a.is_active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{a.is_active?"active":"disabled"}</span>{user?.role==="super_admin"?<button onClick={()=>toggleUser(a.id,a.is_active)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">{a.is_active?"Disable":"Enable"}</button>:null}</div>)}</div></div>
      <aside className="space-y-4"><div className="rounded-xl bg-[#070a45] p-5 text-white"><p className="text-xs font-bold tracking-normal text-white/50">System health</p><div className="mt-4 space-y-3 text-sm"><Line label="Database" value={health?.database||"unknown"}/><Line label="Due campaigns" value={String(health?.due_scheduled_campaigns||0)}/><Line label="Failed publishes" value={String(health?.failed_publication_attempts||0)}/><Line label="Media free" value={`${Math.round((health?.media_free_bytes||0)/1024/1024/1024)} GB`}/><Line label="Backup" value={health?.backup_last_success?(health.backup_stale?"Stale":"Fresh"):"Not recorded"}/><Line label="Backup age" value={health?.backup_age_hours!=null?health.backup_age_hours.toFixed(1)+"h":"—"}/></div><div className={"mt-4 rounded-xl p-3 text-xs "+(health?.backup_stale?"bg-rose-500/15 text-rose-100":"bg-emerald-400/10 text-emerald-100")}><p className="font-semibold">{health?.backup_stale?"Backup attention required":"Backup verification healthy"}</p><p className="mt-1 text-white/60">{health?.latest_db_backup||"No database dump"} · {Math.round((health?.latest_db_backup_bytes||0)/1024/1024)} MB</p><p className="mt-1 text-white/60">{health?.latest_media_backup||"No media archive"} · {Math.round((health?.latest_media_backup_bytes||0)/1024/1024)} MB</p></div></div>{user?.role==="super_admin"&&<form onSubmit={createStaff} className="rounded-xl border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><UserPlus size={18} className="text-[#0866ff]"/><h3 className="font-bold text-slate-900">Create staff account</h3></div><div className="space-y-3"><input value={staffForm.full_name} onChange={e=>setStaffForm(v=>({...v,full_name:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Full name" required/><input type="email" value={staffForm.email} onChange={e=>setStaffForm(v=>({...v,email:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Email" required/><input type="password" value={staffForm.password} onChange={e=>setStaffForm(v=>({...v,password:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Temporary password" minLength={10} required/><select value={staffForm.role} onChange={e=>setStaffForm(v=>({...v,role:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="reviewer">Reviewer</option><option value="publisher">Publisher</option><option value="super_admin">Super Admin</option></select><button className="w-full rounded-xl bg-[#0866ff] px-4 py-3 text-sm font-semibold text-white">Create staff member</button></div></form>}</aside></section>
    {user?.role==="super_admin"&&<><section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">Staff accounts</h2></div><div className="divide-y divide-slate-100">{staffRows.map(s=><div key={s.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold">{s.full_name}</p><p className="mt-1 text-xs text-slate-400">{s.email} · {s.role.replaceAll("_"," ")}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-semibold ${s.is_active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{s.is_active?"active":"disabled"}</span>{s.id!==user.id&&<button onClick={()=>toggleUser(s.id,s.is_active)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold">{s.is_active?"Disable":"Enable"}</button>}</div></div>)}</div></section>
    <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-900">Recent audit activity</h2><p className="mt-1 text-sm text-slate-500">Who changed what and when.</p></div><div className="divide-y divide-slate-100">{auditRows.slice(0,50).map(a=><div key={a.id} className="grid gap-2 p-4 sm:grid-cols-[180px_1fr_auto]"><p className="text-xs font-bold text-slate-400">{a.actor||"System"}</p><div><p className="text-sm font-semibold text-slate-800">{a.action.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-400">{a.entity_type} {a.entity_id?`#${a.entity_id}`:""} {a.detail?`· ${a.detail}`:""}</p></div><p className="text-xs text-slate-400">{new Date(a.created_at).toLocaleString()}</p></div>)}</div></section></>}
  </>}</div></main>
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-5"><div className="text-[#0866ff] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><p className="mt-4 text-2xl font-bold text-slate-900">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>}
function MiniSla({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-bold tracking-normal text-slate-400">{label}</p><p className="mt-1 text-xl font-bold text-slate-900">{value}</p></div>}
function Line({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between border-b border-white/10 pb-2"><span className="text-white/60">{label}</span><span className="font-semibold">{value}</span></div>}
