"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ArrowLeft, CircleDollarSign, Loader2, RefreshCw, ShieldCheck, UserPlus, Users } from "lucide-react";
import { api, getSessionUser, SessionUser } from "@/lib/api";

type Advertiser={id:number;full_name:string;business_name?:string|null;email:string;phone?:string|null;is_active:boolean;created_at:string;campaigns:number;published:number;confirmed_spend:number;currency:string};
type Staff={id:number;full_name:string;email:string;role:string;is_active:boolean;created_at:string};
type Audit={id:number;actor?:string|null;action:string;entity_type:string;entity_id?:string|null;detail?:string|null;created_at:string};
type Health={status:string;database:string;media_total_bytes:number;media_free_bytes:number;failed_publication_attempts:number;due_scheduled_campaigns:number;last_published_at?:string|null;worker_expected:boolean;checked_at:string};

export default function OperationsPage(){
  const router=useRouter();
  const [user,setUser]=useState<SessionUser|null>(null);
  const [advertisers,setAdvertisers]=useState<Advertiser[]>([]);
  const [staffRows,setStaffRows]=useState<Staff[]>([]);
  const [auditRows,setAuditRows]=useState<Audit[]>([]);
  const [health,setHealth]=useState<Health|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [message,setMessage]=useState("");
  const [staffForm,setStaffForm]=useState({full_name:"",email:"",password:"",role:"reviewer"});

  async function load(current?:SessionUser){const u=current||user;if(!u)return;setLoading(true);setError("");try{const [a,h]=await Promise.all([api<Advertiser[]>("/api/v1/admin/advertisers",{},true),api<Health>("/api/v1/admin/system-health",{},true)]);setAdvertisers(a);setHealth(h);if(u.role==="super_admin"){const [s,l]=await Promise.all([api<Staff[]>("/api/v1/admin/staff",{},true),api<Audit[]>("/api/v1/admin/audit?limit=100",{},true)]);setStaffRows(s);setAuditRows(l);}}catch(e){setError(e instanceof Error?e.message:"Unable to load operations");}finally{setLoading(false)}}
  useEffect(()=>{const current=getSessionUser();if(!current||current.role==="advertiser"){router.replace("/login");return;}setUser(current);load(current);},[router]);

  const totals=useMemo(()=>({spend:advertisers.reduce((s,a)=>s+Number(a.confirmed_spend||0),0),campaigns:advertisers.reduce((s,a)=>s+a.campaigns,0),published:advertisers.reduce((s,a)=>s+a.published,0)}),[advertisers]);

  async function createStaff(e:FormEvent){e.preventDefault();setError("");setMessage("");try{await api("/api/v1/admin/staff",{method:"POST",body:JSON.stringify(staffForm)},true);setMessage("Staff account created.");setStaffForm({full_name:"",email:"",password:"",role:"reviewer"});await load();}catch(err){setError(err instanceof Error?err.message:"Unable to create staff account")}}
  async function toggleUser(id:number,is_active:boolean){setError("");try{await api(`/api/v1/admin/users/${id}/state`,{method:"PATCH",body:JSON.stringify({is_active:!is_active})},true);await load();}catch(err){setError(err instanceof Error?err.message:"Unable to update account")}}

  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="sticky top-0 z-20 border-b border-slate-200 bg-white/90 backdrop-blur"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6 lg:px-8"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="min-w-0 flex-1"><h1 className="font-black text-[#070a45]">Operations Control Centre</h1><p className="hidden text-xs text-slate-500 sm:block">Advertisers, staff, system health and audit activity.</p></div><button onClick={()=>load()} className="flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-extrabold text-[#070a45]"><RefreshCw size={16}/> Refresh</button></div></header>
  <div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users/>} label="Advertisers" value={String(advertisers.length)}/><Metric icon={<CircleDollarSign/>} label="Client spend" value={`LSL ${totals.spend.toLocaleString()}`}/><Metric icon={<Activity/>} label="Campaigns" value={String(totals.campaigns)}/><Metric icon={<ShieldCheck/>} label="Worker health" value={health?.worker_expected&&health.database==="ok"?"Ready":"Check"}/></section>
    <section className="mt-6 grid gap-6 xl:grid-cols-[1fr_360px]"><div className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Advertiser accounts</h2><p className="mt-1 text-sm text-slate-500">Commercial activity and account status.</p></div><div className="divide-y divide-slate-100">{advertisers.map(a=><div key={a.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.5fr_.5fr_auto] sm:items-center"><div><p className="font-extrabold">{a.business_name||a.full_name}</p><p className="mt-1 text-xs text-slate-400">{a.email} · {a.campaigns} campaigns · {a.published} published</p></div><p className="font-black text-[#070a45]">{a.currency} {Number(a.confirmed_spend).toLocaleString()}</p><span className={`w-fit rounded-full px-2.5 py-1 text-[11px] font-extrabold ${a.is_active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{a.is_active?"active":"disabled"}</span>{user?.role==="super_admin"?<button onClick={()=>toggleUser(a.id,a.is_active)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold">{a.is_active?"Disable":"Enable"}</button>:null}</div>)}</div></div>
      <aside className="space-y-4"><div className="rounded-[1.5rem] bg-[#070a45] p-5 text-white"><p className="text-xs font-black uppercase tracking-[.16em] text-white/50">System health</p><div className="mt-4 space-y-3 text-sm"><Line label="Database" value={health?.database||"unknown"}/><Line label="Due campaigns" value={String(health?.due_scheduled_campaigns||0)}/><Line label="Failed publishes" value={String(health?.failed_publication_attempts||0)}/><Line label="Media free" value={`${Math.round((health?.media_free_bytes||0)/1024/1024/1024)} GB`}/></div></div>{user?.role==="super_admin"&&<form onSubmit={createStaff} className="rounded-[1.5rem] border border-slate-200 bg-white p-5"><div className="mb-4 flex items-center gap-2"><UserPlus size={18} className="text-[#e31545]"/><h3 className="font-black text-[#070a45]">Create staff account</h3></div><div className="space-y-3"><input value={staffForm.full_name} onChange={e=>setStaffForm(v=>({...v,full_name:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Full name" required/><input type="email" value={staffForm.email} onChange={e=>setStaffForm(v=>({...v,email:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Email" required/><input type="password" value={staffForm.password} onChange={e=>setStaffForm(v=>({...v,password:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" placeholder="Temporary password" minLength={10} required/><select value={staffForm.role} onChange={e=>setStaffForm(v=>({...v,role:e.target.value}))} className="h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option value="reviewer">Reviewer</option><option value="publisher">Publisher</option><option value="super_admin">Super Admin</option></select><button className="w-full rounded-xl bg-[#e31545] px-4 py-3 text-sm font-extrabold text-white">Create staff member</button></div></form>}</aside></section>
    {user?.role==="super_admin"&&<><section className="mt-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-[#070a45]">Staff accounts</h2></div><div className="divide-y divide-slate-100">{staffRows.map(s=><div key={s.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-extrabold">{s.full_name}</p><p className="mt-1 text-xs text-slate-400">{s.email} · {s.role.replaceAll("_"," ")}</p></div><div className="flex items-center gap-3"><span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${s.is_active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-600"}`}>{s.is_active?"active":"disabled"}</span>{s.id!==user.id&&<button onClick={()=>toggleUser(s.id,s.is_active)} className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-extrabold">{s.is_active?"Disable":"Enable"}</button>}</div></div>)}</div></section>
    <section className="mt-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5"><h2 className="font-black text-[#070a45]">Recent audit activity</h2><p className="mt-1 text-sm text-slate-500">Who changed what and when.</p></div><div className="divide-y divide-slate-100">{auditRows.slice(0,50).map(a=><div key={a.id} className="grid gap-2 p-4 sm:grid-cols-[180px_1fr_auto]"><p className="text-xs font-bold text-slate-400">{a.actor||"System"}</p><div><p className="text-sm font-extrabold text-slate-800">{a.action.replaceAll("_"," ")}</p><p className="mt-1 text-xs text-slate-400">{a.entity_type} {a.entity_id?`#${a.entity_id}`:""} {a.detail?`· ${a.detail}`:""}</p></div><p className="text-xs text-slate-400">{new Date(a.created_at).toLocaleString()}</p></div>)}</div></section></>}
  </>}</div></main>
}

function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-5"><div className="text-[#e31545] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><p className="mt-4 text-2xl font-black text-[#070a45]">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>}
function Line({label,value}:{label:string;value:string}){return <div className="flex items-center justify-between border-b border-white/10 pb-2"><span className="text-white/60">{label}</span><span className="font-extrabold">{value}</span></div>}
