"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Loader2, XCircle } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Refund={id:number;payment_id:number;user_id:number;reason:string;status:string;staff_note?:string|null;requested_at:string};

export default function RefundReview(){
 const router=useRouter(); const [rows,setRows]=useState<Refund[]>([]); const [busy,setBusy]=useState<number|null>(null); const [notes,setNotes]=useState<Record<number,string>>({}); const [error,setError]=useState("");
 async function load(){setRows(await api<Refund[]>("/api/v1/refunds",{},true));}
 useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="super_admin"){router.replace("/dashboard");return;}load().catch(e=>setError(e.message));},[router]);
 async function decide(id:number,status:"approved"|"rejected"){setBusy(id);setError("");try{await api("/api/v1/admin/refunds/"+id+"/decision",{method:"POST",body:JSON.stringify({status,staff_note:notes[id]||null})},true);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to decide refund")}finally{setBusy(null)}}
 return <main className="min-h-screen bg-[#f0f2f5]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center gap-4 px-4 sm:px-6"><Link href="/dashboard/payments" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="font-bold text-slate-900">Refund Review</h1><p className="text-xs text-slate-500">Review advertiser refund requests and keep the decision auditable.</p></div></div></header><div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}<section className="overflow-hidden rounded-xl border border-slate-200 bg-white">{rows.length===0?<div className="p-10 text-center text-sm text-slate-500">No refund requests.</div>:<div className="divide-y divide-slate-100">{rows.map(r=><div key={r.id} className="p-5 sm:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-slate-900">Refund #{r.id} · Payment #{r.payment_id}</p><p className="mt-1 text-xs text-slate-400">Advertiser #{r.user_id} · {new Date(r.requested_at).toLocaleString()}</p></div><span className={"rounded-full px-3 py-1 text-xs font-semibold "+(r.status==="approved"?"bg-emerald-50 text-emerald-700":r.status==="rejected"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700")}>{r.status}</span></div><p className="mt-4 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{r.reason}</p>{r.status==="requested"&&<div className="mt-4"><textarea value={notes[r.id]||""} onChange={e=>setNotes(v=>({...v,[r.id]:e.target.value}))} className="min-h-24 w-full rounded-xl border border-slate-200 p-3 text-sm" placeholder="Decision note (optional)"/><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy===r.id} onClick={()=>decide(r.id,"approved")} className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white"><CheckCircle2 size={16}/> Approve refund</button><button disabled={busy===r.id} onClick={()=>decide(r.id,"rejected")} className="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-4 py-2.5 text-sm font-semibold text-rose-700"><XCircle size={16}/> Reject</button></div></div>}</div>)}</div>}</section></div></main>
}