"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Loader2, Mail, Save, Webhook } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Status={email_enabled:boolean;smtp_host?:string|null;smtp_port:number;smtp_username?:string|null;smtp_password_configured:boolean;from_email?:string|null;smtp_use_tls:boolean;webhook_enabled:boolean;webhook_url?:string|null;webhook_bearer_token_configured:boolean};

export default function CommunicationsPage(){
 const router=useRouter();const [form,setForm]=useState({email_enabled:false,smtp_host:"",smtp_port:"587",smtp_username:"",smtp_password:"",from_email:"",smtp_use_tls:true,webhook_enabled:false,webhook_url:"",webhook_bearer_token:""});const [status,setStatus]=useState<Status|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [message,setMessage]=useState("");
 useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="super_admin"){router.replace("/dashboard");return;}api<Status>("/api/v1/system/communications",{},true).then(s=>{setStatus(s);setForm(v=>({...v,email_enabled:s.email_enabled,smtp_host:s.smtp_host||"",smtp_port:String(s.smtp_port||587),smtp_username:s.smtp_username||"",from_email:s.from_email||"",smtp_use_tls:s.smtp_use_tls,webhook_enabled:s.webhook_enabled,webhook_url:s.webhook_url||""}))}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[router]);
 async function save(e:FormEvent){e.preventDefault();setSaving(true);setError("");setMessage("");try{const payload={...form,smtp_port:Number(form.smtp_port),smtp_password:form.smtp_password||null,webhook_bearer_token:form.webhook_bearer_token||null};const s=await api<Status>("/api/v1/system/communications",{method:"PUT",body:JSON.stringify(payload)},true);setStatus(s);setForm(v=>({...v,smtp_password:"",webhook_bearer_token:""}));setMessage("Communication settings saved. Stored passwords and bearer tokens remain hidden.");}catch(e){setError(e instanceof Error?e.message:"Unable to save settings")}finally{setSaving(false)}}
 return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-5xl items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="font-black text-[#070a45]">Notification Delivery</h1><p className="text-xs text-slate-500">Send portal events by email or into a webhook/WhatsApp bridge.</p></div></div></header><div className="mx-auto max-w-5xl p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<form onSubmit={save} className="grid gap-6 lg:grid-cols-2">
 <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]"><Mail size={19}/></div><div><h2 className="font-black text-[#070a45]">Email delivery</h2><p className="text-xs text-slate-500">SMTP for payment, approval and publishing updates.</p></div></div><label className="mt-5 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" checked={form.email_enabled} onChange={e=>setForm(v=>({...v,email_enabled:e.target.checked}))}/> Enable email delivery</label><div className="mt-4 space-y-3"><input className="field" placeholder="SMTP host" value={form.smtp_host} onChange={e=>setForm(v=>({...v,smtp_host:e.target.value}))}/><div className="grid grid-cols-2 gap-2"><input className="field" type="number" placeholder="Port" value={form.smtp_port} onChange={e=>setForm(v=>({...v,smtp_port:e.target.value}))}/><input className="field" placeholder="Username" value={form.smtp_username} onChange={e=>setForm(v=>({...v,smtp_username:e.target.value}))}/></div><input className="field" type="password" placeholder={status?.smtp_password_configured?"New password (leave blank to keep stored)":"SMTP password"} value={form.smtp_password} onChange={e=>setForm(v=>({...v,smtp_password:e.target.value}))}/><input className="field" type="email" placeholder="From email" value={form.from_email} onChange={e=>setForm(v=>({...v,from_email:e.target.value}))}/><label className="flex items-center gap-2 text-xs font-bold text-slate-600"><input type="checkbox" checked={form.smtp_use_tls} onChange={e=>setForm(v=>({...v,smtp_use_tls:e.target.checked}))}/> Use STARTTLS</label></div></section>
 <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#e31545]/10 text-[#e31545]"><Webhook size={19}/></div><div><h2 className="font-black text-[#070a45]">Webhook / WhatsApp bridge</h2><p className="text-xs text-slate-500">POST notification events to your chosen integration service.</p></div></div><label className="mt-5 flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" checked={form.webhook_enabled} onChange={e=>setForm(v=>({...v,webhook_enabled:e.target.checked}))}/> Enable webhook delivery</label><div className="mt-4 space-y-3"><input className="field" placeholder="https://your-service.example/webhook" value={form.webhook_url} onChange={e=>setForm(v=>({...v,webhook_url:e.target.value}))}/><input className="field" type="password" placeholder={status?.webhook_bearer_token_configured?"New bearer token (blank keeps stored)":"Bearer token (optional)"} value={form.webhook_bearer_token} onChange={e=>setForm(v=>({...v,webhook_bearer_token:e.target.value}))}/><div className="rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">The webhook receives the notification plus recipient name, email and phone. This can feed a WhatsApp provider, CRM, automation service or Meloli-owned messaging gateway later.</div></div></section>
 <button disabled={saving} className="flex h-13 items-center justify-center gap-2 rounded-xl bg-[#070a45] px-5 text-sm font-extrabold text-white lg:col-span-2"><Save size={17}/>{saving?"Saving...":"Save notification settings"}</button>
 </form>} </div><style jsx>{".field{height:2.9rem;width:100%;border-radius:.75rem;border:1px solid #e2e8f0;padding:0 .8rem;font-size:.8125rem;outline:none}"}</style></main>
}
