"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Eye, EyeOff, ImageIcon, KeyRound, Loader2, LockKeyhole, Mail, MessageCircle, Save, Settings2, Share2, ShieldCheck, Upload, Webhook } from "lucide-react";
import { API_URL, api, getSessionUser } from "@/lib/api";

type MetaStatus={configured:boolean;connected:boolean;app_id?:string|null;page_id?:string|null;page_name?:string|null;webhook_callback_url?:string|null;graph_api_version?:string|null;app_secret_configured:boolean;page_access_token_configured:boolean;webhook_verify_token_configured:boolean;updated_at?:string|null};
type CommunicationsStatus={email_enabled:boolean;smtp_host?:string|null;smtp_port:number;smtp_username?:string|null;smtp_password_configured:boolean;from_email?:string|null;smtp_use_tls:boolean;webhook_enabled:boolean;webhook_url?:string|null;webhook_bearer_token_configured:boolean;whatsapp_enabled:boolean;whatsapp_phone_number_id?:string|null;whatsapp_access_token_configured:boolean;whatsapp_graph_version:string;whatsapp_template_name?:string|null;whatsapp_template_language:string};
type BrandingStatus={logo_configured:boolean;logo_url?:string|null};

export default function SettingsPage() {
  const router=useRouter();
  const [showSecrets,setShowSecrets]=useState(false);
  const [statusInfo,setStatusInfo]=useState<MetaStatus|null>(null);
  const [communications,setCommunications]=useState<CommunicationsStatus|null>(null);
  const [branding,setBranding]=useState<BrandingStatus|null>(null);
  const [form,setForm]=useState({app_id:"",app_secret:"",page_id:"",page_access_token:"",webhook_verify_token:"",webhook_callback_url:"",graph_api_version:""});
  const [commForm,setCommForm]=useState({email_enabled:false,smtp_host:"",smtp_port:"587",smtp_username:"",smtp_password:"",from_email:"",smtp_use_tls:true,webhook_enabled:false,webhook_url:"",webhook_bearer_token:"",whatsapp_enabled:false,whatsapp_phone_number_id:"",whatsapp_access_token:"",whatsapp_graph_version:"v24.0",whatsapp_template_name:"",whatsapp_template_language:"en"});
  const [testEmail,setTestEmail]=useState(""); const [testPhone,setTestPhone]=useState("");
  const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");

  useEffect(()=>{const user=getSessionUser();if(!user||user.role!=="super_admin"){router.replace("/login");return;}Promise.all([api<MetaStatus>("/api/v1/system/integrations/meta",{},true),api<CommunicationsStatus>("/api/v1/system/communications",{},true),api<BrandingStatus>("/api/v1/system/branding",{},true)]).then(([s,comm,brand])=>{setStatusInfo(s);setForm(v=>({...v,app_id:s.app_id||"",page_id:s.page_id||"",webhook_callback_url:s.webhook_callback_url||"",graph_api_version:s.graph_api_version||""}));setCommunications(comm);setBranding(brand);setCommForm(v=>({...v,email_enabled:comm.email_enabled,smtp_host:comm.smtp_host||"",smtp_port:String(comm.smtp_port||587),smtp_username:comm.smtp_username||"",from_email:comm.from_email||"",smtp_use_tls:comm.smtp_use_tls,webhook_enabled:comm.webhook_enabled,webhook_url:comm.webhook_url||"",whatsapp_enabled:comm.whatsapp_enabled,whatsapp_phone_number_id:comm.whatsapp_phone_number_id||"",whatsapp_graph_version:comm.whatsapp_graph_version||"v24.0",whatsapp_template_name:comm.whatsapp_template_name||"",whatsapp_template_language:comm.whatsapp_template_language||"en"}));}).catch(e=>setError(e.message));},[router]);
  const change=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));

  async function save(){setBusy(true);setError("");setMessage("");try{const payload:Record<string,string|null>={app_id:form.app_id,page_id:form.page_id,webhook_callback_url:form.webhook_callback_url||null,graph_api_version:form.graph_api_version||null};if(form.app_secret)payload.app_secret=form.app_secret;if(form.page_access_token)payload.page_access_token=form.page_access_token;if(form.webhook_verify_token)payload.webhook_verify_token=form.webhook_verify_token;const s=await api<MetaStatus>("/api/v1/system/integrations/meta",{method:"PUT",body:JSON.stringify(payload)},true);setStatusInfo(s);setForm(v=>({...v,app_secret:"",page_access_token:"",webhook_verify_token:""}));setMessage("Meta configuration saved securely.");}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setBusy(false);}}
  async function testConnection(){setBusy(true);setError("");setMessage("");try{const s=await api<MetaStatus>("/api/v1/system/integrations/meta/test",{method:"POST"},true);setStatusInfo(s);setMessage(s.connected?`Connection verified${s.page_name?` for ${s.page_name}`:""}.`:"Connection could not be verified.");}catch(e){setError(e instanceof Error?e.message:"Connection test failed");}finally{setBusy(false);}}
  async function saveCommunications(){setBusy(true);setError("");setMessage("");try{const payload={email_enabled:commForm.email_enabled,smtp_host:commForm.smtp_host||null,smtp_port:Number(commForm.smtp_port||587),smtp_username:commForm.smtp_username||null,from_email:commForm.from_email||null,smtp_use_tls:commForm.smtp_use_tls,webhook_enabled:commForm.webhook_enabled,webhook_url:commForm.webhook_url||null,whatsapp_enabled:commForm.whatsapp_enabled,whatsapp_phone_number_id:commForm.whatsapp_phone_number_id||null,whatsapp_graph_version:commForm.whatsapp_graph_version||"v24.0",whatsapp_template_name:commForm.whatsapp_template_name||null,whatsapp_template_language:commForm.whatsapp_template_language||"en",...(commForm.smtp_password?{smtp_password:commForm.smtp_password}:{}),...(commForm.webhook_bearer_token?{webhook_bearer_token:commForm.webhook_bearer_token}:{}),...(commForm.whatsapp_access_token?{whatsapp_access_token:commForm.whatsapp_access_token}:{})};const s=await api<CommunicationsStatus>("/api/v1/system/communications",{method:"PUT",body:JSON.stringify(payload)},true);setCommunications(s);setCommForm(v=>({...v,smtp_password:"",webhook_bearer_token:"",whatsapp_access_token:""}));setMessage("Notification delivery settings saved securely.");}catch(e){setError(e instanceof Error?e.message:"Unable to save notification settings");}finally{setBusy(false);}}
  async function testEmailDelivery(){if(!testEmail){setError("Enter a test email address.");return;}setBusy(true);setError("");setMessage("");try{await api("/api/v1/system/communications/test-email",{method:"POST",body:JSON.stringify({recipient:testEmail})},true);setMessage("Test email sent successfully.");}catch(e){setError(e instanceof Error?e.message:"SMTP test failed");}finally{setBusy(false);}}
  async function testWhatsAppDelivery(){if(!testPhone){setError("Enter a WhatsApp number including country code.");return;}setBusy(true);setError("");setMessage("");try{await api("/api/v1/system/communications/test-whatsapp",{method:"POST",body:JSON.stringify({recipient:testPhone})},true);setMessage("WhatsApp test request accepted by Meta.");}catch(e){setError(e instanceof Error?e.message:"WhatsApp test failed");}finally{setBusy(false);}}
  async function uploadLogo(file:File){setBusy(true);setError("");setMessage("");try{const body=new FormData();body.append("file",file);const brand=await api<BrandingStatus>("/api/v1/system/branding/logo",{method:"POST",body},true);setBranding(brand);setMessage("Meloli logo updated. New quotations, invoices, receipts and statements will use it automatically.");}catch(e){setError(e instanceof Error?e.message:"Unable to upload logo");}finally{setBusy(false);}}

  return <main className="min-h-screen bg-[#f0f2f5] text-slate-900">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6 lg:px-8"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 text-slate-900"><ArrowLeft size={18}/></Link><div className="min-w-0 flex-1"><h1 className="truncate text-lg font-bold text-slate-900">System Configuration</h1><p className="hidden text-xs text-slate-500 sm:block">Manage publishing integrations and protected platform credentials</p></div><button disabled={busy} onClick={save} className="flex items-center gap-2 rounded-xl bg-[#0866ff] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy?<Loader2 size={17} className="animate-spin"/>:<Save size={17}/>}<span className="hidden sm:inline">Save changes</span></button></div></header>
    <div className="mx-auto grid max-w-[1500px] gap-6 p-4 sm:p-6 lg:grid-cols-[270px_1fr] lg:p-8"><aside className="h-fit rounded-xl border border-slate-200 bg-white p-3"><button className="flex w-full items-center gap-3 rounded-xl bg-[#070a45] px-4 py-3 text-left text-sm font-semibold text-white"><Share2 size={18}/> Facebook / Meta</button><button className="mt-1 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-bold text-slate-500"><Settings2 size={18}/> General settings</button><button className="mt-1 flex w-full items-center gap-3 rounded-xl px-4 py-3 text-left text-sm font-bold text-slate-500"><ShieldCheck size={18}/> Security & audit</button></aside>
      <section className="space-y-6"><div className="rounded-xl bg-[#070a45] p-6 text-white sm:p-8"><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold tracking-normal text-white/50">Publishing integration</p><h2 className="mt-2 text-3xl font-bold tracking-tight">Facebook Page connection</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/60">Stored secret values never return to this browser. To rotate one, enter only the replacement value and save.</p></div><div className="flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-xs font-semibold text-white/70"><span className={`h-2.5 w-2.5 rounded-full ${statusInfo?.connected?"bg-emerald-400":"bg-amber-400"}`}/>{statusInfo?.connected?(statusInfo.page_name||"Connected"):statusInfo?.configured?"Configured, not verified":"Not configured"}</div></div></div>
        <div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><div className="mb-6 flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-blue-600"><Share2 size={22}/></div><div><h3 className="font-bold text-slate-900">Meta application credentials</h3><p className="mt-1 text-sm leading-6 text-slate-500">Configure the Meta app and Meloli Airwaves Page used for approved publishing.</p></div></div>
          <div className="grid gap-5 md:grid-cols-2"><Field label="Meta App ID" value={form.app_id} onChange={v=>change("app_id",v)} placeholder="Enter Meta App ID"/><SecretField label="Meta App Secret" value={form.app_secret} onChange={v=>change("app_secret",v)} placeholder={statusInfo?.app_secret_configured?"Stored securely — enter to replace":"Enter app secret"} show={showSecrets}/><Field label="Facebook Page ID" value={form.page_id} onChange={v=>change("page_id",v)} placeholder="Enter Meloli Page ID"/><Field label="Graph API version" value={form.graph_api_version} onChange={v=>change("graph_api_version",v)} placeholder="e.g. vXX.X"/><div className="md:col-span-2"><SecretField label="Page access token" value={form.page_access_token} onChange={v=>change("page_access_token",v)} placeholder={statusInfo?.page_access_token_configured?"Stored securely — enter to replace":"Enter Page access token"} show={showSecrets}/></div><SecretField label="Webhook verify token" value={form.webhook_verify_token} onChange={v=>change("webhook_verify_token",v)} placeholder={statusInfo?.webhook_verify_token_configured?"Stored securely — enter to replace":"Enter verify token"} show={showSecrets}/><Field label="Webhook callback URL" value={form.webhook_callback_url} onChange={v=>change("webhook_callback_url",v)} placeholder="https://your-domain/api/v1/meta/webhook"/></div>
          <div className="mt-6 flex flex-col gap-3 border-t border-slate-100 pt-6 sm:flex-row sm:items-center sm:justify-between"><button onClick={()=>setShowSecrets(v=>!v)} className="flex items-center gap-2 text-sm font-semibold text-slate-600">{showSecrets?<EyeOff size={17}/>:<Eye size={17}/>} {showSecrets?"Hide entered secrets":"Show entered secrets"}</button><div className="flex gap-2"><button disabled={busy} onClick={testConnection} className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-900 disabled:opacity-50">Test connection</button><button disabled={busy} onClick={save} className="rounded-xl bg-[#0866ff] px-4 py-3 text-sm font-semibold text-white disabled:opacity-50">Save integration</button></div></div>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7">
          <div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-[#e7f3ff] text-slate-900"><ImageIcon size={22}/></div><div><h3 className="font-bold text-slate-900">Meloli document branding</h3><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-500">Upload the approved Meloli logo once. The system uses it automatically on quotations, invoices, receipts and corporate statements.</p></div></div>
            {branding?.logo_configured&&branding.logo_url?<div className="flex h-20 w-44 items-center justify-center rounded-xl border border-slate-200 bg-slate-50 p-3"><img src={API_URL+branding.logo_url} alt="Meloli logo" className="max-h-full max-w-full object-contain"/></div>:<div className="rounded-xl bg-amber-50 px-4 py-3 text-xs font-bold text-amber-700">No logo uploaded yet</div>}
          </div>
          <div className="mt-5 flex flex-col gap-3 border-t border-slate-100 pt-5 sm:flex-row sm:items-center sm:justify-between"><p className="text-xs leading-5 text-slate-500">PNG, JPEG or WebP · maximum 3 MB · transparent PNG recommended.</p><label className="inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-[#070a45] px-5 py-3 text-sm font-semibold text-white"><Upload size={17}/>{branding?.logo_configured?"Replace logo":"Upload Meloli logo"}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)uploadLogo(file);e.currentTarget.value="";}}/></label></div>
        </div>
        <div className="rounded-xl border border-slate-200 bg-white p-5 sm:p-7">
          <div className="mb-6 flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-rose-50 text-[#0866ff]"><Mail size={22}/></div><div><h3 className="font-bold text-slate-900">Advertiser notifications</h3><p className="mt-1 text-sm leading-6 text-slate-500">Deliver payment, approval and publishing updates by email and optionally forward the same events to a WhatsApp or automation webhook.</p></div></div>
          <div className="grid gap-5 lg:grid-cols-2">
            <div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><p className="font-bold text-slate-900">Email delivery</p><p className="mt-1 text-xs text-slate-500">SMTP credentials are stored encrypted.</p></div><Toggle checked={commForm.email_enabled} onChange={v=>setCommForm(s=>({...s,email_enabled:v}))}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><Field label="SMTP host" value={commForm.smtp_host} onChange={v=>setCommForm(s=>({...s,smtp_host:v}))} placeholder="smtp.example.com"/><Field label="SMTP port" value={commForm.smtp_port} onChange={v=>setCommForm(s=>({...s,smtp_port:v}))} placeholder="587"/><Field label="SMTP username" value={commForm.smtp_username} onChange={v=>setCommForm(s=>({...s,smtp_username:v}))} placeholder="notifications@example.com"/><SecretField label="SMTP password" value={commForm.smtp_password} onChange={v=>setCommForm(s=>({...s,smtp_password:v}))} placeholder={communications?.smtp_password_configured?"Stored securely — enter to replace":"Enter SMTP password"} show={showSecrets}/><div className="sm:col-span-2"><Field label="From email" value={commForm.from_email} onChange={v=>setCommForm(s=>({...s,from_email:v}))} placeholder="notifications@meloli.co.ls"/></div><label className="sm:col-span-2 flex items-center gap-3 text-sm font-bold text-slate-600"><input type="checkbox" checked={commForm.smtp_use_tls} onChange={e=>setCommForm(s=>({...s,smtp_use_tls:e.target.checked}))}/> Use STARTTLS/TLS</label><div className="sm:col-span-2 grid gap-2 sm:grid-cols-[1fr_auto]"><input value={testEmail} onChange={e=>setTestEmail(e.target.value)} className="h-11 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none" placeholder="Test recipient email"/><button type="button" disabled={busy} onClick={testEmailDelivery} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-900">Send test email</button></div></div></div>
            <div className="rounded-xl border border-slate-200 p-4"><div className="flex items-center justify-between gap-3"><div><p className="flex items-center gap-2 font-bold text-slate-900"><Webhook size={17}/> Webhook delivery</p><p className="mt-1 text-xs text-slate-500">Connect WhatsApp, CRM or another notification service.</p></div><Toggle checked={commForm.webhook_enabled} onChange={v=>setCommForm(s=>({...s,webhook_enabled:v}))}/></div><div className="mt-4 space-y-3"><Field label="Webhook URL" value={commForm.webhook_url} onChange={v=>setCommForm(s=>({...s,webhook_url:v}))} placeholder="https://automation.example.com/meloli"/><SecretField label="Bearer token" value={commForm.webhook_bearer_token} onChange={v=>setCommForm(s=>({...s,webhook_bearer_token:v}))} placeholder={communications?.webhook_bearer_token_configured?"Stored securely — enter to replace":"Optional bearer token"} show={showSecrets}/><p className="rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">The webhook receives the advertiser name, email, phone and the notification payload. A WhatsApp provider can use the phone number to deliver the message.</p></div></div>
            <div className="rounded-xl border border-slate-200 p-4 lg:col-span-2"><div className="flex items-center justify-between gap-3"><div><p className="flex items-center gap-2 font-bold text-slate-900"><MessageCircle size={17}/> WhatsApp Cloud API</p><p className="mt-1 text-xs text-slate-500">Direct Meta WhatsApp delivery using an approved business template with title and message body parameters.</p></div><Toggle checked={commForm.whatsapp_enabled} onChange={v=>setCommForm(s=>({...s,whatsapp_enabled:v}))}/></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Field label="Phone Number ID" value={commForm.whatsapp_phone_number_id} onChange={v=>setCommForm(s=>({...s,whatsapp_phone_number_id:v}))} placeholder="Meta WhatsApp Phone Number ID"/><Field label="Graph API version" value={commForm.whatsapp_graph_version} onChange={v=>setCommForm(s=>({...s,whatsapp_graph_version:v}))} placeholder="v24.0"/><SecretField label="Access token" value={commForm.whatsapp_access_token} onChange={v=>setCommForm(s=>({...s,whatsapp_access_token:v}))} placeholder={communications?.whatsapp_access_token_configured?"Stored securely — enter to replace":"Permanent/system-user access token"} show={showSecrets}/><Field label="Approved template name" value={commForm.whatsapp_template_name} onChange={v=>setCommForm(s=>({...s,whatsapp_template_name:v}))} placeholder="meloli_status_update"/><Field label="Template language" value={commForm.whatsapp_template_language} onChange={v=>setCommForm(s=>({...s,whatsapp_template_language:v}))} placeholder="en"/><div className="grid gap-2 sm:grid-cols-[1fr_auto]"><input value={testPhone} onChange={e=>setTestPhone(e.target.value)} className="h-12 rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm outline-none" placeholder="2665xxxxxxx"/><button type="button" disabled={busy} onClick={testWhatsAppDelivery} className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-900">Send test</button></div></div><p className="mt-3 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-800">The approved WhatsApp template should contain two body placeholders in order: notification title, then notification message. Business-initiated WhatsApp messages are sent as templates rather than unrestricted free-form text.</p></div>
          </div>
          <div className="mt-5 flex justify-end"><button disabled={busy} onClick={saveCommunications} className="rounded-xl bg-[#070a45] px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">Save notification delivery</button></div>
        </div>
        {(message||error)&&<div className={`flex items-center gap-3 rounded-xl border px-5 py-4 text-sm font-semibold ${error?"border-rose-200 bg-rose-50 text-rose-700":"border-emerald-200 bg-emerald-50 text-emerald-700"}`}><CheckCircle2 size={19}/>{error||message}</div>}
        <div className="grid gap-4 md:grid-cols-3"><Info icon={<LockKeyhole/>} title="Secrets stay server-side" text="Saved app secrets and access tokens are encrypted before database storage."/><Info icon={<KeyRound/>} title="Replace without revealing" text="The dashboard only reports whether each secret exists; it never reads the saved value."/><Info icon={<ShieldCheck/>} title="Super Admin controlled" text="The backend protects this configuration with the super-admin role."/></div>
      </section></div>
  </main>;
}

function Field({label,placeholder,value,onChange}:{label:string;placeholder:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-bold uppercase tracking-[.08em] text-slate-500">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold outline-none focus:border-[#0866ff] focus:bg-white" placeholder={placeholder}/></label>}
function SecretField({label,placeholder,show,value,onChange}:{label:string;placeholder:string;show:boolean;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.08em] text-slate-500">{label}<LockKeyhole size={13}/></span><input value={value} onChange={e=>onChange(e.target.value)} type={show?"text":"password"} autoComplete="new-password" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 px-4 text-sm font-semibold outline-none focus:border-[#0866ff] focus:bg-white" placeholder={placeholder}/></label>}
function Info({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-[1.35rem] border border-slate-200 bg-white p-5"><div className="mb-4 grid h-10 w-10 place-items-center rounded-xl bg-[#e7f3ff] text-slate-900 [&>svg]:h-5 [&>svg]:w-5">{icon}</div><h4 className="font-bold text-slate-900">{title}</h4><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
function Toggle({checked,onChange}:{checked:boolean;onChange:(v:boolean)=>void}){return <button type="button" onClick={()=>onChange(!checked)} className={`relative h-7 w-12 rounded-full transition ${checked?"bg-[#0866ff]":"bg-slate-200"}`} aria-pressed={checked}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white shadow transition ${checked?"left-6":"left-1"}`}/></button>}

