"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Download, FileText, Loader2, ReceiptText, WalletCards } from "lucide-react";
import { API_URL, api, getSessionUser, getToken } from "@/lib/api";

type Campaign={id:number;title:string};
type Payment={id:number;campaign_id:number;amount:number;currency:string;method:string;reference?:string|null;status:string;paid_at?:string|null;created_at:string};
type Row=Payment&{campaignTitle:string};
type CommercialAccount={corporate?:{active:boolean;credit_limit:number;credit_used:number;available_credit:number;billing_cycle_day:number;utilization_percent:number;low_credit:boolean;overdue:boolean}|null;subscription?:{id:number;plan?:string|null;plan_code?:string|null;period_start:string;period_end:string;remaining_posts:number;active:boolean}|null};
type CorporateInvoice={id:number;invoice_number:string;amount:number;amount_paid:number;balance:number;currency:string;status:string;period_key:string;issued_at:string;due_at:string;paid_at?:string|null};
type CorporateSettlement={id:number;amount:number;method:string;reference?:string|null;settled_at:string};
type CreditNote={id:number;credit_note_number:string;invoice_id?:number|null;payment_id:number;refund_request_id?:number|null;amount:number;applied_to_invoice_amount:number;currency:string;reason:string;issued_at:string};

export default function BillingPage(){
  const router=useRouter();
  const [rows,setRows]=useState<Row[]>([]);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [commercial,setCommercial]=useState<CommercialAccount|null>(null);
  const [corporateInvoices,setCorporateInvoices]=useState<CorporateInvoice[]>([]);
  const [corporateSettlements,setCorporateSettlements]=useState<CorporateSettlement[]>([]);
  const [creditNotes,setCreditNotes]=useState<CreditNote[]>([]);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [downloading,setDownloading]=useState<string|null>(null);

  useEffect(()=>{const user=getSessionUser();if(!user||user.role!=="advertiser"){router.replace("/login");return;}Promise.all([api<Campaign[]>("/api/v1/campaigns",{},true),api<CommercialAccount>("/api/v1/commercial/my-account",{},true),api<CorporateInvoice[]>("/api/v1/commercial/my-corporate/invoices",{},true).catch(()=>[]),api<CorporateSettlement[]>("/api/v1/commercial/my-corporate/settlements",{},true).catch(()=>[]),api<CreditNote[]>("/api/v1/commercial/my-corporate/credit-notes",{},true).catch(()=>[])]).then(async ([campaigns,account,invoices,settlements,notes])=>{setCampaigns(campaigns);setCommercial(account);setCorporateInvoices(invoices);setCorporateSettlements(settlements);setCreditNotes(notes);const groups=await Promise.all(campaigns.map(async c=>{const payments=await api<Payment[]>(`/api/v1/campaigns/${c.id}/payments`,{},true);return payments.map(p=>({...p,campaignTitle:c.title}))}));setRows(groups.flat().sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()));}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[router]);

  async function download(path:string,filename:string,key:string){setDownloading(key);setError("");try{const token=getToken();const response=await fetch(`${API_URL}${path}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){const body=await response.json().catch(()=>({detail:"Unable to generate document"}));throw new Error(body.detail||"Unable to generate document");}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to download document");}finally{setDownloading(null)}}

  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center gap-4 px-4 sm:px-6"><Link href="/advertiser" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Payments & Documents</h1><p className="text-xs text-slate-500">Quotations, invoices, payment status and receipts.</p></div><Link href="/advertiser/refunds" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-extrabold text-[#070a45]">Refund requests</Link></div></header><div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<>
    {commercial?.corporate&&<section className="mb-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="bg-[#070a45] p-5 text-white sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-white/45">Corporate account</p><h2 className="mt-2 text-2xl font-black">Advertising credit & billing</h2><p className="mt-2 text-sm text-white/60">Billing cycle day {commercial.corporate.billing_cycle_day}. Download your branded Meloli statement or current invoice at any time.</p></div><span className={"w-fit rounded-full px-3 py-1.5 text-xs font-extrabold "+(commercial.corporate.overdue?"bg-rose-500 text-white":commercial.corporate.low_credit?"bg-amber-300 text-amber-950":"bg-emerald-400 text-emerald-950")}>{commercial.corporate.overdue?"Payment overdue":commercial.corporate.low_credit?"Credit running low":"Account current"}</span></div></div><div className="grid gap-4 p-5 sm:grid-cols-3 sm:p-6"><Mini label="Credit limit" value={"LSL "+commercial.corporate.credit_limit.toFixed(2)}/><Mini label="Outstanding" value={"LSL "+commercial.corporate.credit_used.toFixed(2)}/><Mini label="Available" value={"LSL "+commercial.corporate.available_credit.toFixed(2)}/></div><div className="flex flex-col gap-2 border-t border-slate-100 p-5 sm:flex-row sm:justify-end sm:p-6"><button onClick={()=>download("/api/v1/commercial/my-corporate/statement.pdf","meloli-corporate-statement.pdf","corp-statement")} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-extrabold text-[#070a45]"><FileText size={16}/>{downloading==="corp-statement"?"Preparing...":"Corporate statement"}</button><button onClick={()=>download("/api/v1/commercial/my-corporate/invoice.pdf","meloli-corporate-invoice.pdf","corp-invoice")} className="flex items-center justify-center gap-2 rounded-xl bg-[#e31545] px-4 py-3 text-sm font-extrabold text-white"><Download size={16}/>{downloading==="corp-invoice"?"Preparing...":"Current invoice"}</button></div></section>}
    {corporateInvoices.length>0&&<section className="mb-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Corporate invoice history</h2><p className="mt-1 text-sm text-slate-500">Monthly invoices keep their original amount, due date and payment status.</p></div><div className="divide-y divide-slate-100">{corporateInvoices.map(inv=><div key={inv.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.6fr_.6fr_auto] sm:items-center sm:px-6"><div><p className="font-extrabold text-[#070a45]">{inv.invoice_number}</p><p className="mt-1 text-xs text-slate-400">Period {inv.period_key} · due {new Date(inv.due_at).toLocaleDateString()}</p></div><div><span className={"rounded-full px-2.5 py-1 text-[11px] font-extrabold "+(inv.status==="paid"||inv.status==="closed"||inv.status==="credited"?"bg-emerald-50 text-emerald-700":inv.status==="overdue"?"bg-rose-50 text-rose-700":inv.status==="partial"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700")}>{inv.status}</span></div><div><p className="font-black text-[#070a45]">{inv.currency} {inv.balance.toFixed(2)}</p><p className="mt-1 text-[11px] text-slate-400">of {inv.currency} {inv.amount.toFixed(2)}</p></div><button onClick={()=>download("/api/v1/commercial/my-corporate/invoices/"+inv.id+"/pdf",inv.invoice_number+".pdf","corp-inv-"+inv.id)} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45]"><Download size={15}/>{downloading==="corp-inv-"+inv.id?"Preparing...":"PDF"}</button></div>)}</div></section>}
    {creditNotes.length>0&&<section className="mb-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Corporate credit notes</h2><p className="mt-1 text-sm text-slate-500">Approved corporate refunds and credits, linked back to the original payment and invoice where applicable.</p></div><div className="divide-y divide-slate-100">{creditNotes.map(n=><div key={n.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.7fr_.7fr_auto] sm:items-center sm:px-6"><div><p className="font-extrabold text-[#070a45]">{n.credit_note_number}</p><p className="mt-1 text-xs text-slate-400">Payment #{n.payment_id}{n.invoice_id?" · Invoice #"+n.invoice_id:""} · {new Date(n.issued_at).toLocaleDateString()}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Credit value</p><p className="mt-1 font-black text-[#e31545]">{n.currency} {n.amount.toFixed(2)}</p></div><div><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Applied to invoice</p><p className="mt-1 font-black text-[#070a45]">{n.currency} {n.applied_to_invoice_amount.toFixed(2)}</p></div><button onClick={()=>download("/api/v1/commercial/my-corporate/credit-notes/"+n.id+"/pdf",n.credit_note_number+".pdf","cn-"+n.id)} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45]"><Download size={15}/>{downloading==="cn-"+n.id?"Preparing...":"Credit note"}</button><p className="sm:col-span-4 text-xs leading-5 text-slate-500">{n.reason}</p></div>)}</div></section>}
    {corporateSettlements.length>0&&<section className="mb-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Corporate payment receipts</h2><p className="mt-1 text-sm text-slate-500">Proof of payments recorded against your corporate advertising account.</p></div><div className="divide-y divide-slate-100">{corporateSettlements.map(s=><div key={s.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.7fr_.7fr_auto] sm:items-center sm:px-6"><div><p className="font-extrabold text-[#070a45]">Settlement #{s.id}</p><p className="mt-1 text-xs text-slate-400">{new Date(s.settled_at).toLocaleString()}</p></div><p className="text-sm font-bold text-slate-600">{s.method.replaceAll("_"," ")}</p><div><p className="font-black text-[#070a45]">LSL {s.amount.toFixed(2)}</p><p className="mt-1 text-[11px] text-slate-400">{s.reference||"No reference"}</p></div><button onClick={()=>download("/api/v1/commercial/my-corporate/settlements/"+s.id+"/receipt.pdf","meloli-corporate-receipt-"+s.id+".pdf","corp-rct-"+s.id)} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45]"><Download size={15}/>{downloading==="corp-rct-"+s.id?"Preparing...":"Receipt"}</button></div>)}</div></section>}
    {commercial?.subscription&&<section className="mb-6 rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#e31545]">Monthly advertising plan</p><h2 className="mt-1 font-black text-[#070a45]">{commercial.subscription.plan||commercial.subscription.plan_code||"Meloli plan"}</h2><p className="mt-2 text-sm text-slate-500">{commercial.subscription.remaining_posts} posts remaining · expires {new Date(commercial.subscription.period_end).toLocaleDateString()}</p></div><span className={"w-fit rounded-full px-3 py-1.5 text-xs font-extrabold "+(commercial.subscription.active?"bg-emerald-50 text-emerald-700":"bg-rose-50 text-rose-700")}>{commercial.subscription.active?"Active":"Expired"}</span></div></section>}
    {campaigns.length>0&&<section className="mb-6 rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Commercial documents</h2><p className="mt-1 text-sm text-slate-500">Download a quotation or invoice for any campaign.</p></div><div className="divide-y divide-slate-100">{campaigns.map(c=><div key={c.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-extrabold text-slate-900">{c.title}</p><p className="mt-1 text-xs text-slate-400">Campaign #{c.id}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>download(`/api/v1/campaigns/${c.id}/quotation.pdf`,`meloli-quotation-${c.id}.pdf`,`q-${c.id}`)} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45]"><FileText size={15}/>{downloading===`q-${c.id}`?"Preparing...":"Quotation"}</button><button onClick={()=>download(`/api/v1/campaigns/${c.id}/invoice.pdf`,`meloli-invoice-${c.id}.pdf`,`i-${c.id}`)} className="flex items-center gap-2 rounded-xl bg-[#070a45] px-3 py-2.5 text-sm font-extrabold text-white"><Download size={15}/>{downloading===`i-${c.id}`?"Preparing...":"Invoice"}</button></div></div>)}</div></section>}
    {rows.length===0?<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><WalletCards className="mx-auto text-slate-300"/><h2 className="mt-4 font-black text-[#070a45]">No payments yet</h2><p className="mt-2 text-sm text-slate-500">Payment records will appear here after you submit a payment reference.</p></div>:<section className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Billing history</h2><p className="mt-1 text-sm text-slate-500">Confirmed transactions include downloadable PDF receipts.</p></div><div className="divide-y divide-slate-100">{rows.map(p=><div key={p.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.65fr_.6fr_auto] sm:items-center"><div><p className="font-extrabold text-slate-900">{p.campaignTitle}</p><p className="mt-1 text-xs text-slate-400">Payment #{p.id} · {p.method.replaceAll("_"," ")} · {p.reference||"No reference"}</p></div><div><span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${p.status==="paid"?"bg-emerald-50 text-emerald-700":p.status==="failed"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700"}`}>{p.status}</span></div><p className="font-black text-[#070a45]">{p.currency} {Number(p.amount).toFixed(2)}</p>{p.status==="paid"?<button disabled={downloading===`r-${p.id}`} onClick={()=>download(`/api/v1/payments/${p.id}/receipt.pdf`,`meloli-receipt-${p.id}.pdf`,`r-${p.id}`)} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45] disabled:opacity-50">{downloading===`r-${p.id}`?<Loader2 size={16} className="animate-spin"/>:<Download size={16}/>} Receipt</button>:<ReceiptText size={18} className="text-slate-300"/>}</div>)}</div></section>}
  </>}</div></main>
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-4"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-lg font-black text-[#070a45]">{value}</p></div>}
