"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, Download, FileText, Loader2, ReceiptText, WalletCards } from "lucide-react";
import { API_URL, api, getSessionUser, getToken } from "@/lib/api";

type Campaign={id:number;title:string};
type Payment={id:number;campaign_id:number;amount:number;currency:string;method:string;reference?:string|null;status:string;paid_at?:string|null;created_at:string};
type Row=Payment&{campaignTitle:string};

export default function BillingPage(){
  const router=useRouter();
  const [rows,setRows]=useState<Row[]>([]);
  const [campaigns,setCampaigns]=useState<Campaign[]>([]);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState("");
  const [downloading,setDownloading]=useState<string|null>(null);

  useEffect(()=>{const user=getSessionUser();if(!user||user.role!=="advertiser"){router.replace("/login");return;}api<Campaign[]>("/api/v1/campaigns",{},true).then(async campaigns=>{setCampaigns(campaigns);const groups=await Promise.all(campaigns.map(async c=>{const payments=await api<Payment[]>(`/api/v1/campaigns/${c.id}/payments`,{},true);return payments.map(p=>({...p,campaignTitle:c.title}))}));setRows(groups.flat().sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime()));}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[router]);

  async function download(path:string,filename:string,key:string){setDownloading(key);setError("");try{const token=getToken();const response=await fetch(`${API_URL}${path}`,{headers:{Authorization:`Bearer ${token}`}});if(!response.ok){const body=await response.json().catch(()=>({detail:"Unable to generate document"}));throw new Error(body.detail||"Unable to generate document");}const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to download document");}finally{setDownloading(null)}}

  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center gap-4 px-4 sm:px-6"><Link href="/advertiser" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="font-black text-[#070a45]">Payments & Documents</h1><p className="text-xs text-slate-500">Quotations, invoices, payment status and receipts.</p></div></div></header><div className="mx-auto max-w-6xl p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{loading?<div className="grid min-h-72 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<>
    {campaigns.length>0&&<section className="mb-6 rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Commercial documents</h2><p className="mt-1 text-sm text-slate-500">Download a quotation or invoice for any campaign.</p></div><div className="divide-y divide-slate-100">{campaigns.map(c=><div key={c.id} className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-extrabold text-slate-900">{c.title}</p><p className="mt-1 text-xs text-slate-400">Campaign #{c.id}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>download(`/api/v1/campaigns/${c.id}/quotation.pdf`,`meloli-quotation-${c.id}.pdf`,`q-${c.id}`)} className="flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45]"><FileText size={15}/>{downloading===`q-${c.id}`?"Preparing...":"Quotation"}</button><button onClick={()=>download(`/api/v1/campaigns/${c.id}/invoice.pdf`,`meloli-invoice-${c.id}.pdf`,`i-${c.id}`)} className="flex items-center gap-2 rounded-xl bg-[#070a45] px-3 py-2.5 text-sm font-extrabold text-white"><Download size={15}/>{downloading===`i-${c.id}`?"Preparing...":"Invoice"}</button></div></div>)}</div></section>}
    {rows.length===0?<div className="rounded-[1.6rem] border border-dashed border-slate-300 bg-white p-10 text-center"><WalletCards className="mx-auto text-slate-300"/><h2 className="mt-4 font-black text-[#070a45]">No payments yet</h2><p className="mt-2 text-sm text-slate-500">Payment records will appear here after you submit a payment reference.</p></div>:<section className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Billing history</h2><p className="mt-1 text-sm text-slate-500">Confirmed transactions include downloadable PDF receipts.</p></div><div className="divide-y divide-slate-100">{rows.map(p=><div key={p.id} className="grid gap-3 p-5 sm:grid-cols-[1fr_.65fr_.6fr_auto] sm:items-center"><div><p className="font-extrabold text-slate-900">{p.campaignTitle}</p><p className="mt-1 text-xs text-slate-400">Payment #{p.id} · {p.method.replaceAll("_"," ")} · {p.reference||"No reference"}</p></div><div><span className={`rounded-full px-2.5 py-1 text-[11px] font-extrabold ${p.status==="paid"?"bg-emerald-50 text-emerald-700":p.status==="failed"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700"}`}>{p.status}</span></div><p className="font-black text-[#070a45]">{p.currency} {Number(p.amount).toFixed(2)}</p>{p.status==="paid"?<button disabled={downloading===`r-${p.id}`} onClick={()=>download(`/api/v1/payments/${p.id}/receipt.pdf`,`meloli-receipt-${p.id}.pdf`,`r-${p.id}`)} className="flex items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 py-2.5 text-sm font-extrabold text-[#070a45] disabled:opacity-50">{downloading===`r-${p.id}`?<Loader2 size={16} className="animate-spin"/>:<Download size={16}/>} Receipt</button>:<ReceiptText size={18} className="text-slate-300"/>}</div>)}</div></section>}
  </>}</div></main>
}