"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, Loader2, PackagePlus, Save, Tag } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Package = {id:number;code:string;name:string;description:string;price:number;currency:string;posts_included:number;max_media_items:number;allow_video:boolean;allow_carousel:boolean;active:boolean};
const empty={code:"",name:"",description:"",price:"",currency:"LSL",posts_included:"1",max_media_items:"10",allow_video:true,allow_carousel:true,active:true};

export default function PackagesPage(){
  const [items,setItems]=useState<Package[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<number|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const load=()=>api<Package[]>("/api/v1/admin/packages",{},true).then(setItems).catch(e=>setError(e.message));
  useEffect(()=>{const u=getSessionUser(); if(!u||u.role!=="super_admin"){window.location.href="/login";return;} load();},[]);
  function edit(p:Package){setEditing(p.id);setForm({code:p.code,name:p.name,description:p.description,price:String(p.price),currency:p.currency,posts_included:String(p.posts_included),max_media_items:String(p.max_media_items),allow_video:p.allow_video,allow_carousel:p.allow_carousel,active:p.active});window.scrollTo({top:0,behavior:"smooth"});}
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const body=JSON.stringify({...form,price:Number(form.price),posts_included:Number(form.posts_included),max_media_items:Number(form.max_media_items)});await api(editing?`/api/v1/admin/packages/${editing}`:"/api/v1/admin/packages",{method:editing?"PUT":"POST",body},true);setForm(empty);setEditing(null);await load();}catch(err){setError(err instanceof Error?err.message:"Unable to save package");}finally{setBusy(false);}}
  return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Advertising packages</h1><p className="text-xs text-slate-500">Control pricing, post allowances and package availability</p></div><Tag className="text-[#e31545]"/></div></header>
  <div className="mx-auto grid max-w-[1500px] gap-6 p-4 sm:p-6 lg:grid-cols-[390px_1fr] lg:p-8"><form onSubmit={submit} className="h-fit rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]"><PackagePlus size={20}/></div><div><h2 className="font-black text-[#070a45]">{editing?"Edit package":"New package"}</h2><p className="text-xs text-slate-500">Changes affect new adverts immediately.</p></div></div><div className="mt-6 space-y-4"><Field label="Package code"><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} placeholder="STANDARD"/></Field><Field label="Package name"><input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Standard Post"/></Field><Field label="Description"><textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Price"><input type="number" min="1" step="0.01" required value={form.price} onChange={e=>setForm({...form,price:e.target.value})}/></Field><Field label="Posts"><input type="number" min="1" required value={form.posts_included} onChange={e=>setForm({...form,posts_included:e.target.value})}/></Field></div><Field label="Max media per advert"><input type="number" min="1" max="10" required value={form.max_media_items} onChange={e=>setForm({...form,max_media_items:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><label className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 text-sm font-bold"><span>Allow video</span><input type="checkbox" checked={form.allow_video} onChange={e=>setForm({...form,allow_video:e.target.checked})}/></label><label className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 text-sm font-bold"><span>Allow carousel</span><input type="checkbox" checked={form.allow_carousel} onChange={e=>setForm({...form,allow_carousel:e.target.checked})}/></label></div><label className="flex items-center justify-between rounded-2xl border border-slate-200 p-4 text-sm font-bold"><span>Package active</span><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/></label>{error&&<div className="rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}<button disabled={busy} className="flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#e31545] font-extrabold text-white disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={18}/>:<Save size={18}/>} {editing?"Save changes":"Create package"}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(empty)}} className="h-11 w-full rounded-xl border border-slate-200 text-sm font-bold text-slate-500">Cancel editing</button>}</div></form>
  <section className="rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Current pricing</h2><p className="mt-1 text-sm text-slate-500">These are the packages advertisers can buy.</p></div><div className="divide-y divide-slate-100">{items.map(p=><button key={p.id} onClick={()=>edit(p)} className="grid w-full gap-3 p-5 text-left hover:bg-slate-50 sm:grid-cols-[1fr_auto_auto] sm:items-center sm:px-6"><div><div className="flex flex-wrap items-center gap-2"><span className="font-black text-[#070a45]">{p.name}</span><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-black uppercase tracking-wider text-slate-500">{p.code}</span>{!p.active&&<span className="rounded-full bg-rose-50 px-2 py-1 text-[10px] font-black text-rose-700">Inactive</span>}</div><p className="mt-1 max-w-2xl text-sm text-slate-500">{p.description}</p></div><div className="text-sm font-bold text-slate-500">{p.posts_included} post{p.posts_included===1?"":"s"}<p className="mt-1 text-[11px] font-semibold text-slate-400">Up to {p.max_media_items} media · {p.allow_video?"video":"no video"} · {p.allow_carousel?"carousel":"single media"}</p></div><div className="text-xl font-black text-[#070a45]">M {Number(p.price).toFixed(2)}</div></button>)}{items.length===0&&<div className="p-10 text-center text-sm text-slate-400">No packages configured.</div>}</div></section></div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-black uppercase tracking-[.08em] text-slate-500">{label}</span><div className="rounded-xl border border-slate-200 bg-slate-50 px-3 focus-within:border-[#070a45] [&_input]:h-11 [&_input]:w-full [&_input]:bg-transparent [&_input]:outline-none [&_textarea]:w-full [&_textarea]:bg-transparent [&_textarea]:py-3 [&_textarea]:outline-none">{children}</div></label>}
