"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, BadgePercent, Building2, CircleDollarSign, Loader2, RefreshCw, TrendingUp, Users } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Partner={id:number;name:string;code:string;commission_percent:number;contact_email?:string|null;active:boolean;referred_advertisers:number;paid_transactions:number;attributed_revenue:number;commission_earned:number;commission_paid:number;commission_due:number;created_at:string};
type Forecast={currency:string;method:string;trailing_90_day_revenue:number;trailing_monthly_run_rate:number;month_to_date_revenue:number;current_month_pace:number;forecast_next_30_days:number;forecast_next_90_days:number;generated_at:string};

export default function GrowthPage(){
 const router=useRouter(); const [partners,setPartners]=useState<Partner[]>([]); const [forecast,setForecast]=useState<Forecast|null>(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [message,setMessage]=useState("");
 const [form,setForm]=useState({name:"",code:"",commission_percent:"10",contact_email:""}); const [payoutPartner,setPayoutPartner]=useState(""); const [payoutAmount,setPayoutAmount]=useState(""); const [payoutRef,setPayoutRef]=useState("");
 async function load(){setLoading(true);setError("");try{const [p,f]=await Promise.all([api<Partner[]>("/api/v1/admin/referral-partners",{},true),api<Forecast>("/api/v1/admin/growth/forecast",{},true)]);setPartners(p);setForecast(f);}catch(e){setError(e instanceof Error?e.message:"Unable to load growth data")}finally{setLoading(false)}}
 useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="super_admin"){router.replace("/dashboard");return;}load();},[router]);
 async function create(e:FormEvent){e.preventDefault();setError("");try{await api("/api/v1/admin/referral-partners",{method:"POST",body:JSON.stringify({name:form.name,code:form.code,commission_percent:Number(form.commission_percent||0),contact_email:form.contact_email||null,active:true})},true);setForm({name:"",code:"",commission_percent:"10",contact_email:""});setMessage("Referral partner created.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create partner")}}
 async function togglePartner(id:number,active:boolean){setError("");try{await api("/api/v1/admin/referral-partners/"+id+"/state",{method:"PATCH",body:JSON.stringify({active:!active})},true);setMessage(active?"Referral partner disabled.":"Referral partner enabled.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to update referral partner")}}
 async function payout(e:FormEvent){e.preventDefault();if(!payoutPartner)return;setError("");try{await api("/api/v1/admin/referral-partners/"+payoutPartner+"/payouts",{method:"POST",body:JSON.stringify({amount:Number(payoutAmount),reference:payoutRef||null})},true);setPayoutAmount("");setPayoutRef("");setMessage("Partner payout recorded.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to record payout")}}
 const due=partners.reduce((s,p)=>s+p.commission_due,0), revenue=partners.reduce((s,p)=>s+p.attributed_revenue,0), referred=partners.reduce((s,p)=>s+p.referred_advertisers,0);
 return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Growth & Referrals</h1><p className="text-xs text-slate-500">Partner acquisition, commission exposure and revenue forecasting.</p></div><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><RefreshCw size={16}/></button></div></header><div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{message&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}{loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<>
 <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<Users/>} label="Referred advertisers" value={String(referred)}/><Metric icon={<CircleDollarSign/>} label="Attributed revenue" value={"LSL "+revenue.toLocaleString(undefined,{minimumFractionDigits:2})}/><Metric icon={<BadgePercent/>} label="Commission due" value={"LSL "+due.toLocaleString(undefined,{minimumFractionDigits:2})}/><Metric icon={<TrendingUp/>} label="30-day forecast" value={"LSL "+Number(forecast?.forecast_next_30_days||0).toLocaleString(undefined,{minimumFractionDigits:2})}/></section>
 {forecast&&<section className="mt-6 rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#e31545]">Revenue outlook</p><h2 className="mt-1 text-xl font-black text-[#070a45]">Executive run-rate forecast</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">{forecast.method}. This is an operating forecast, not a guaranteed result.</p></div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="90-day actual" value={"LSL "+forecast.trailing_90_day_revenue.toFixed(2)}/><Mini label="Monthly run rate" value={"LSL "+forecast.trailing_monthly_run_rate.toFixed(2)}/><Mini label="Month to date" value={"LSL "+forecast.month_to_date_revenue.toFixed(2)}/><Mini label="90-day forecast" value={"LSL "+forecast.forecast_next_90_days.toFixed(2)}/></div></div></section>}
 <div className="mt-6 grid gap-6 xl:grid-cols-[380px_1fr]"><div className="space-y-6"><form onSubmit={create} className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Header icon={<Building2/>} title="New referral partner" text="Create an auditable partner code and commission rate."/><div className="mt-5 space-y-3"><input className="field" required value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} placeholder="Partner name"/><input className="field uppercase" required value={form.code} onChange={e=>setForm(v=>({...v,code:e.target.value.toUpperCase()}))} placeholder="Partner code"/><input className="field" type="number" min="0" max="100" step="0.01" value={form.commission_percent} onChange={e=>setForm(v=>({...v,commission_percent:e.target.value}))} placeholder="Commission %"/><input className="field" type="email" value={form.contact_email} onChange={e=>setForm(v=>({...v,contact_email:e.target.value}))} placeholder="Contact email (optional)"/><button className="primary">Create partner</button></div></form><form onSubmit={payout} className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Header icon={<CircleDollarSign/>} title="Record partner payout" text="Record commission payments already made outside the portal."/><div className="mt-5 space-y-3"><select className="field" value={payoutPartner} onChange={e=>setPayoutPartner(e.target.value)} required><option value="">Select partner</option>{partners.filter(p=>p.commission_due>0).map(p=><option key={p.id} value={p.id}>{p.name} · LSL {p.commission_due.toFixed(2)} due</option>)}</select><input className="field" required type="number" min="0.01" step="0.01" value={payoutAmount} onChange={e=>setPayoutAmount(e.target.value)} placeholder="Amount"/><input className="field" value={payoutRef} onChange={e=>setPayoutRef(e.target.value)} placeholder="Reference"/><button className="secondary">Record payout</button></div></form></div>
 <section className="overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Partner performance</h2><p className="mt-1 text-sm text-slate-500">Commission is calculated only from currently confirmed paid transactions.</p></div>{partners.length===0?<div className="p-10 text-center text-sm text-slate-500">No referral partners yet.</div>:<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-[10px] font-black uppercase tracking-wider text-slate-400"><th className="px-5 py-3">Partner</th><th className="px-5 py-3">Advertisers</th><th className="px-5 py-3">Revenue</th><th className="px-5 py-3">Rate</th><th className="px-5 py-3">Earned</th><th className="px-5 py-3">Paid</th><th className="px-5 py-3">Due</th></tr></thead><tbody>{partners.map(p=><tr key={p.id} className="border-b border-slate-50"><td className="px-5 py-4"><div className="flex items-center gap-2"><p className="font-extrabold text-[#070a45]">{p.name}</p><span className={"rounded-full px-2 py-0.5 text-[10px] font-extrabold "+(p.active?"bg-emerald-50 text-emerald-700":"bg-slate-100 text-slate-500")}>{p.active?"Active":"Disabled"}</span></div><p className="mt-1 text-[11px] text-slate-400">{p.code}{p.contact_email?" · "+p.contact_email:""}</p><button type="button" onClick={()=>togglePartner(p.id,p.active)} className="mt-2 rounded-lg border border-slate-200 px-2.5 py-1.5 text-[11px] font-extrabold text-[#070a45]">{p.active?"Disable partner":"Enable partner"}</button></td><td className="px-5 py-4">{p.referred_advertisers}</td><td className="px-5 py-4 font-extrabold text-[#070a45]">LSL {p.attributed_revenue.toFixed(2)}</td><td className="px-5 py-4">{p.commission_percent}%</td><td className="px-5 py-4">LSL {p.commission_earned.toFixed(2)}</td><td className="px-5 py-4">LSL {p.commission_paid.toFixed(2)}</td><td className="px-5 py-4 font-black text-[#e31545]">LSL {p.commission_due.toFixed(2)}</td></tr>)}</tbody></table></div>}</section></div>
 </>}</div><style jsx>{".field{height:2.8rem;width:100%;border-radius:.75rem;border:1px solid #e2e8f0;padding:0 .75rem;font-size:.8125rem;outline:none}.primary,.secondary{height:2.8rem;width:100%;border-radius:.75rem;font-size:.8125rem;font-weight:800}.primary{background:#e31545;color:white}.secondary{background:#070a45;color:white}"}</style></main>
}
function Header({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]">{icon}</div><h2 className="font-black text-[#070a45]">{title}</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-5"><div className="text-[#e31545] [&>svg]:h-5 [&>svg]:w-5">{icon}</div><p className="mt-4 text-2xl font-black text-[#070a45]">{value}</p><p className="mt-1 text-xs font-bold text-slate-500">{label}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-[#070a45]">{value}</p></div>}
