"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, BadgePercent, Building2, CalendarRange, Loader2 } from "lucide-react";
import { API_URL, api, getSessionUser, getToken } from "@/lib/api";

type Promo={id:number;code:string;percent_off:number;fixed_off:number;uses:number;max_uses?:number|null;active:boolean;paid_payments?:number;attributed_revenue?:number;discount_value?:number};
type Plan={id:number;code:string;name:string;monthly_price:number;included_posts:number;active:boolean};
type Advertiser={id:number;full_name:string;business_name?:string|null;email:string};
type Subscription={id:number;user_id:number;advertiser:string;plan_id:number;plan:string;period_start:string;period_end:string;remaining_posts:number;active:boolean};
type Statement={advertiser:{id:number;name:string;email:string};account:{credit_limit:number;credit_used:number;available_credit:number;billing_cycle_day:number;active:boolean};transactions:{payment_id:number;campaign_id:number;campaign:string;amount:number;currency:string;created_at:string;status:string}[]};
type ReceivableRow={user_id:number;advertiser:string;email?:string|null;credit_limit:number;billing_cycle_day:number;outstanding:number;available:number;utilization_percent:number;overdue:boolean;low_credit:boolean};
type Receivables={accounts:number;outstanding_total:number;overdue_total:number;overdue_accounts:number;low_credit_accounts:number;rows:ReceivableRow[]};
type CorporateInvoice={id:number;invoice_number:string;user_id?:number|null;advertiser?:string|null;amount:number;amount_paid:number;credited_amount?:number;balance:number;currency:string;status:string;period_key:string;issued_at:string;due_at:string;paid_at?:string|null};
type CreditNote={id:number;credit_note_number:string;user_id?:number|null;advertiser?:string|null;invoice_id?:number|null;invoice_number?:string|null;payment_id:number;refund_request_id?:number|null;amount:number;applied_to_invoice_amount:number;currency:string;reason:string;issued_at:string};

export default function CommercialPage(){
 const router=useRouter();
 const [promos,setPromos]=useState<Promo[]>([]);
 const [plans,setPlans]=useState<Plan[]>([]);
 const [advertisers,setAdvertisers]=useState<Advertiser[]>([]);
 const [subscriptions,setSubscriptions]=useState<Subscription[]>([]);
 const [statement,setStatement]=useState<Statement|null>(null);
 const [receivables,setReceivables]=useState<Receivables|null>(null);
 const [corporateInvoices,setCorporateInvoices]=useState<CorporateInvoice[]>([]);
 const [creditNotes,setCreditNotes]=useState<CreditNote[]>([]);
 const [lastSettlementId,setLastSettlementId]=useState<number|null>(null);
 const [emailingInvoice,setEmailingInvoice]=useState<number|null>(null);
 const [loading,setLoading]=useState(true);
 const [error,setError]=useState("");
 const [message,setMessage]=useState("");
 const [promo,setPromo]=useState({code:"",percent_off:"",fixed_off:"",max_uses:""});
 const [plan,setPlan]=useState({code:"",name:"",monthly_price:"",included_posts:""});
 const [advertiserId,setAdvertiserId]=useState("");
 const [creditLimit,setCreditLimit]=useState("");
 const [billingCycleDay,setBillingCycleDay]=useState("28");
 const [planId,setPlanId]=useState("");
 const [settlementMethod,setSettlementMethod]=useState("bank_transfer");
 const [settlementReference,setSettlementReference]=useState("");
 const [settlementAmount,setSettlementAmount]=useState("");

 async function load(){
   setLoading(true);setError("");
   try{
     const [p,pl,a,s,r,ci,cn]=await Promise.all([
       api<Promo[]>("/api/v1/admin/promos/performance",{},true),
       api<Plan[]>("/api/v1/admin/subscription-plans",{},true),
       api<Advertiser[]>("/api/v1/admin/advertisers",{},true),
       api<Subscription[]>("/api/v1/admin/subscriptions",{},true),
       api<Receivables>("/api/v1/admin/receivables/summary",{},true),
       api<CorporateInvoice[]>("/api/v1/admin/corporate-invoices",{},true),
       api<CreditNote[]>("/api/v1/admin/credit-notes",{},true)
     ]);
     setPromos(p);setPlans(pl);setAdvertisers(a);setSubscriptions(s);setReceivables(r);setCorporateInvoices(ci);setCreditNotes(cn);
   }catch(e){setError(e instanceof Error?e.message:"Unable to load commercial settings")}
   finally{setLoading(false)}
 }
 useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="super_admin"){router.replace("/dashboard");return;}load();},[router]);

 async function createPromo(e:FormEvent){e.preventDefault();setError("");
   try{await api("/api/v1/admin/promos",{method:"POST",body:JSON.stringify({code:promo.code,percent_off:Number(promo.percent_off||0),fixed_off:Number(promo.fixed_off||0),max_uses:promo.max_uses?Number(promo.max_uses):null,active:true})},true);setPromo({code:"",percent_off:"",fixed_off:"",max_uses:""});setMessage("Promotion created.");await load();}
   catch(e){setError(e instanceof Error?e.message:"Unable to create promotion")}
 }
 async function createPlan(e:FormEvent){e.preventDefault();setError("");
   try{await api("/api/v1/admin/subscription-plans",{method:"POST",body:JSON.stringify({code:plan.code,name:plan.name,description:"",monthly_price:Number(plan.monthly_price),included_posts:Number(plan.included_posts),active:true})},true);setPlan({code:"",name:"",monthly_price:"",included_posts:""});setMessage("Monthly plan created.");await load();}
   catch(e){setError(e instanceof Error?e.message:"Unable to create plan")}
 }
 async function saveCorporate(){if(!advertiserId)return;setError("");
   try{await api("/api/v1/admin/advertisers/"+advertiserId+"/corporate",{method:"PUT",body:JSON.stringify({credit_limit:Number(creditLimit||0),billing_cycle_day:Number(billingCycleDay||28),active:true})},true);setMessage("Corporate credit updated.");}
   catch(e){setError(e instanceof Error?e.message:"Unable to save credit")}
 }
 async function assignPlan(){if(!advertiserId||!planId)return;setError("");
   try{await api("/api/v1/admin/subscriptions",{method:"POST",body:JSON.stringify({user_id:Number(advertiserId),plan_id:Number(planId),months:1})},true);setMessage("Monthly plan assigned.");await load();}
   catch(e){setError(e instanceof Error?e.message:"Unable to assign plan")}
 }
 async function renewSubscription(id:number){setError("");try{await api("/api/v1/admin/subscriptions/"+id+"/renew",{method:"POST",body:JSON.stringify({months:1})},true);setMessage("Subscription renewed for one month.");await load();}catch(e){setError(e instanceof Error?e.message:"Unable to renew subscription")}}
 async function loadStatement(){if(!advertiserId)return;setError("");try{setStatement(await api<Statement>("/api/v1/admin/advertisers/"+advertiserId+"/corporate/statement",{},true));}catch(e){setStatement(null);setError(e instanceof Error?e.message:"Unable to load corporate statement")}}
 async function settleAccount(){if(!advertiserId)return;setError("");try{const result=await api<{settlement_id:number}>("/api/v1/admin/advertisers/"+advertiserId+"/corporate/settle",{method:"POST",body:JSON.stringify({amount:settlementAmount?Number(settlementAmount):null,method:settlementMethod,reference:settlementReference||null})},true);setLastSettlementId(result.settlement_id);setSettlementReference("");setSettlementAmount("");setMessage("Corporate payment recorded and receipt created.");await loadStatement();await load();}catch(e){setError(e instanceof Error?e.message:"Unable to settle corporate balance")}}
 async function emailInvoice(id:number){setEmailingInvoice(id);setError("");try{const result=await api<{emailed_to:string}>("/api/v1/admin/corporate-invoices/"+id+"/email",{method:"POST"},true);setMessage("Invoice emailed to "+result.emailed_to+".");}catch(e){setError(e instanceof Error?e.message:"Unable to email invoice")}finally{setEmailingInvoice(null)}}
 async function downloadPdf(path:string,filename:string){setError("");try{const token=getToken();const response=await fetch(API_URL+path,{headers:token?{Authorization:"Bearer "+token}:{}});if(!response.ok)throw new Error("Unable to generate PDF");const blob=await response.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to download PDF")}}
 async function downloadStatement(){if(!advertiserId)return;await downloadPdf("/api/v1/admin/advertisers/"+advertiserId+"/corporate/statement.pdf","meloli-corporate-statement-"+advertiserId+".pdf")}
 async function downloadInvoice(userId?:number){const id=userId||Number(advertiserId);if(!id)return;await downloadPdf("/api/v1/admin/advertisers/"+id+"/corporate/invoice.pdf","meloli-corporate-invoice-"+id+".pdf")}
 async function downloadSettlementReceipt(){if(!lastSettlementId)return;await downloadPdf("/api/v1/admin/corporate-settlements/"+lastSettlementId+"/receipt.pdf","meloli-corporate-receipt-"+lastSettlementId+".pdf")}

 return <main className="min-h-screen bg-[#f5f6fa] text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-[1500px] items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="font-black text-[#070a45]">Commercial Growth</h1><p className="text-xs text-slate-500">Promotions, corporate credit and monthly advertising plans.</p></div></div></header>
  <div className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8">
   {error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
   {message&&<div className="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}
   {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:<div className="grid gap-6 xl:grid-cols-3">
    <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Header icon={<BadgePercent/>} title="Promo codes" text="Offer controlled discounts without changing public package prices."/><form onSubmit={createPromo} className="mt-5 space-y-3"><input className="field uppercase" placeholder="Code" value={promo.code} onChange={e=>setPromo(v=>({...v,code:e.target.value.toUpperCase()}))} required/><div className="grid grid-cols-2 gap-2"><input className="field" type="number" min="0" max="100" placeholder="% off" value={promo.percent_off} onChange={e=>setPromo(v=>({...v,percent_off:e.target.value}))}/><input className="field" type="number" min="0" placeholder="LSL off" value={promo.fixed_off} onChange={e=>setPromo(v=>({...v,fixed_off:e.target.value}))}/></div><input className="field" type="number" min="1" placeholder="Max uses" value={promo.max_uses} onChange={e=>setPromo(v=>({...v,max_uses:e.target.value}))}/><button className="primary">Create promotion</button></form><div className="mt-5 space-y-2">{promos.map(p=><div key={p.id} className="rounded-xl bg-slate-50 p-3"><b className="text-sm text-[#070a45]">{p.code}</b><p className="mt-1 text-xs text-slate-500">{p.percent_off>0?p.percent_off+"% off":"LSL "+p.fixed_off+" off"} · {p.uses}{p.max_uses?"/"+p.max_uses:""} uses</p><div className="mt-2 grid grid-cols-2 gap-2"><div className="rounded-lg bg-white p-2"><p className="text-[9px] font-black uppercase text-slate-400">Revenue</p><p className="text-xs font-extrabold text-[#070a45]">LSL {Number(p.attributed_revenue||0).toFixed(2)}</p></div><div className="rounded-lg bg-white p-2"><p className="text-[9px] font-black uppercase text-slate-400">Discount given</p><p className="text-xs font-extrabold text-[#e31545]">LSL {Number(p.discount_value||0).toFixed(2)}</p></div></div></div>)}</div></section>
    <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Header icon={<CalendarRange/>} title="Monthly plans" text="Create recurring plans for advertisers who post frequently."/><form onSubmit={createPlan} className="mt-5 space-y-3"><input className="field uppercase" placeholder="Plan code" value={plan.code} onChange={e=>setPlan(v=>({...v,code:e.target.value.toUpperCase()}))} required/><input className="field" placeholder="Plan name" value={plan.name} onChange={e=>setPlan(v=>({...v,name:e.target.value}))} required/><div className="grid grid-cols-2 gap-2"><input className="field" type="number" min="0" placeholder="Monthly LSL" value={plan.monthly_price} onChange={e=>setPlan(v=>({...v,monthly_price:e.target.value}))} required/><input className="field" type="number" min="1" placeholder="Posts" value={plan.included_posts} onChange={e=>setPlan(v=>({...v,included_posts:e.target.value}))} required/></div><button className="primary">Create monthly plan</button></form><div className="mt-5 space-y-2">{plans.map(p=><div key={p.id} className="rounded-xl bg-slate-50 p-3"><b className="text-sm text-[#070a45]">{p.name}</b><p className="mt-1 text-xs text-slate-500">LSL {p.monthly_price.toFixed(2)} · {p.included_posts} adverts</p></div>)}</div></section>
    <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5"><Header icon={<Building2/>} title="Corporate accounts" text="Give approved clients controlled credit or assign a monthly plan."/><div className="mt-5 space-y-3"><select className="field" value={advertiserId} onChange={e=>setAdvertiserId(e.target.value)}><option value="">Select advertiser</option>{advertisers.map(a=><option key={a.id} value={a.id}>{a.business_name||a.full_name} · {a.email}</option>)}</select><input className="field" type="number" min="0" placeholder="Corporate credit limit" value={creditLimit} onChange={e=>setCreditLimit(e.target.value)}/><input className="field" type="number" min="1" max="28" placeholder="Billing cycle day" value={billingCycleDay} onChange={e=>setBillingCycleDay(e.target.value)}/><button onClick={saveCorporate} className="primary" type="button">Save credit account</button><div className="my-4 border-t border-slate-100"/><select className="field" value={planId} onChange={e=>setPlanId(e.target.value)}><option value="">Select monthly plan</option>{plans.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={assignPlan} className="secondary" type="button">Assign monthly plan</button></div></section>
   </div>}
   {!loading&&receivables&&<section className="mt-6 rounded-[1.6rem] border border-slate-200 bg-white p-5 sm:p-6">
    <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><Header icon={<Building2/>} title="Accounts receivable" text="Corporate balances, billing-cycle risk and available credit across approved advertisers."/><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Outstanding" value={"LSL "+receivables.outstanding_total.toFixed(2)}/><Mini label="Overdue" value={"LSL "+receivables.overdue_total.toFixed(2)}/><Mini label="Overdue accts" value={String(receivables.overdue_accounts)}/><Mini label="Low credit" value={String(receivables.low_credit_accounts)}/></div></div>
    <div className="mt-5 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-[10px] font-black uppercase tracking-wider text-slate-400"><th className="px-3 py-3">Advertiser</th><th className="px-3 py-3">Outstanding</th><th className="px-3 py-3">Credit used</th><th className="px-3 py-3">Billing day</th><th className="px-3 py-3">Status</th><th className="px-3 py-3 text-right">Document</th></tr></thead><tbody>{receivables.rows.map(r=><tr key={r.user_id} className="border-b border-slate-50"><td className="px-3 py-4"><p className="font-extrabold text-[#070a45]">{r.advertiser}</p><p className="mt-1 text-[11px] text-slate-400">{r.email}</p></td><td className="px-3 py-4 font-extrabold text-[#070a45]">LSL {r.outstanding.toFixed(2)}</td><td className="px-3 py-4">{r.utilization_percent.toFixed(1)}%</td><td className="px-3 py-4">Day {r.billing_cycle_day}</td><td className="px-3 py-4"><span className={"rounded-full px-2.5 py-1 font-extrabold "+(r.overdue?"bg-rose-50 text-rose-700":r.low_credit?"bg-amber-50 text-amber-700":"bg-emerald-50 text-emerald-700")}>{r.overdue?"Overdue":r.low_credit?"Low credit":"Current"}</span></td><td className="px-3 py-4 text-right"><button type="button" onClick={()=>downloadInvoice(r.user_id)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 font-extrabold text-[#070a45]">Invoice PDF</button></td></tr>)}</tbody></table></div>
   </section>}
   {!loading&&corporateInvoices.length>0&&<section className="mt-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Monthly corporate invoices</h2><p className="mt-1 text-sm text-slate-500">Persistent billing-cycle invoices with due dates and settlement status.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-[10px] font-black uppercase tracking-wider text-slate-400"><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Advertiser</th><th className="px-5 py-3">Period</th><th className="px-5 py-3">Due</th><th className="px-5 py-3">Balance</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">PDF</th></tr></thead><tbody>{corporateInvoices.map(inv=><tr key={inv.id} className="border-b border-slate-50"><td className="px-5 py-4 font-extrabold text-[#070a45]">{inv.invoice_number}</td><td className="px-5 py-4">{inv.advertiser||("User #"+inv.user_id)}</td><td className="px-5 py-4">{inv.period_key}</td><td className="px-5 py-4">{new Date(inv.due_at).toLocaleDateString()}</td><td className="px-5 py-4 font-extrabold text-[#070a45]">{inv.currency} {inv.balance.toFixed(2)}</td><td className="px-5 py-4"><span className={"rounded-full px-2.5 py-1 font-extrabold "+(inv.status==="paid"||inv.status==="closed"||inv.status==="credited"?"bg-emerald-50 text-emerald-700":inv.status==="overdue"?"bg-rose-50 text-rose-700":inv.status==="partial"?"bg-amber-50 text-amber-700":"bg-blue-50 text-blue-700")}>{inv.status}</span></td><td className="px-5 py-4"><div className="flex justify-end gap-2"><button type="button" onClick={()=>downloadPdf("/api/v1/admin/corporate-invoices/"+inv.id+"/pdf",inv.invoice_number+".pdf")} className="rounded-lg border border-slate-200 px-3 py-2 font-extrabold text-[#070a45]">Download</button><button type="button" disabled={emailingInvoice===inv.id} onClick={()=>emailInvoice(inv.id)} className="rounded-lg bg-[#070a45] px-3 py-2 font-extrabold text-white disabled:opacity-50">{emailingInvoice===inv.id?"Sending...":"Email"}</button></div></td></tr>)}</tbody></table></div></section>}
   {!loading&&creditNotes.length>0&&<section className="mt-6 overflow-hidden rounded-[1.6rem] border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-black text-[#070a45]">Corporate credit notes</h2><p className="mt-1 text-sm text-slate-500">Refund credits linked to their original corporate payment and invoice wherever the payment had already been billed.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead><tr className="border-b border-slate-100 text-[10px] font-black uppercase tracking-wider text-slate-400"><th className="px-5 py-3">Credit note</th><th className="px-5 py-3">Advertiser</th><th className="px-5 py-3">Invoice</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Credit</th><th className="px-5 py-3">Applied</th><th className="px-5 py-3 text-right">PDF</th></tr></thead><tbody>{creditNotes.map(n=><tr key={n.id} className="border-b border-slate-50"><td className="px-5 py-4"><p className="font-extrabold text-[#070a45]">{n.credit_note_number}</p><p className="mt-1 text-[11px] text-slate-400">{new Date(n.issued_at).toLocaleDateString()}</p></td><td className="px-5 py-4">{n.advertiser||("User #"+n.user_id)}</td><td className="px-5 py-4">{n.invoice_number||"Not yet invoiced"}</td><td className="px-5 py-4">#{n.payment_id}</td><td className="px-5 py-4 font-extrabold text-[#e31545]">{n.currency} {n.amount.toFixed(2)}</td><td className="px-5 py-4 font-extrabold text-[#070a45]">{n.currency} {n.applied_to_invoice_amount.toFixed(2)}</td><td className="px-5 py-4 text-right"><button type="button" onClick={()=>downloadPdf("/api/v1/admin/credit-notes/"+n.id+"/pdf",n.credit_note_number+".pdf")} className="rounded-lg border border-slate-200 px-3 py-2 font-extrabold text-[#070a45]">Download</button></td></tr>)}</tbody></table></div></section>}
   {!loading&&<div className="mt-6 grid gap-6 xl:grid-cols-2">
    <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5">
      <Header icon={<CalendarRange/>} title="Active subscriptions" text="Renew monthly plans and see remaining advertising allocation."/>
      <div className="mt-5 space-y-3">{subscriptions.length===0?<p className="text-sm text-slate-500">No subscriptions yet.</p>:subscriptions.slice(0,10).map(s=><div key={s.id} className="flex flex-col gap-3 rounded-xl bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-extrabold text-[#070a45]">{s.advertiser}</p><p className="mt-1 text-xs text-slate-500">{s.plan} · {s.remaining_posts} posts left · ends {new Date(s.period_end).toLocaleDateString()}</p></div><button onClick={()=>renewSubscription(s.id)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-extrabold text-[#070a45]">{s.active?"Renew 1 month":"Reactivate"}</button></div>)}</div>
    </section>
    <section className="rounded-[1.6rem] border border-slate-200 bg-white p-5">
      <Header icon={<Building2/>} title="Corporate statement" text="Review credit usage for the selected advertiser and clear the balance when payment is received."/>
      <div className="mt-5 grid gap-2 sm:grid-cols-3"><button type="button" onClick={loadStatement} className="secondary">Load statement</button><button type="button" onClick={downloadStatement} className="secondary">Statement PDF</button><button type="button" onClick={()=>downloadInvoice()} className="primary">Invoice PDF</button></div>
      {statement&&<div className="mt-4"><div className="grid grid-cols-3 gap-2"><Mini label="Limit" value={"LSL "+statement.account.credit_limit.toFixed(2)}/><Mini label="Used" value={"LSL "+statement.account.credit_used.toFixed(2)}/><Mini label="Available" value={"LSL "+statement.account.available_credit.toFixed(2)}/></div><div className="mt-4 max-h-56 space-y-2 overflow-auto">{statement.transactions.length===0?<p className="text-xs text-slate-500">No corporate-credit transactions.</p>:statement.transactions.map(t=><div key={t.payment_id} className="flex justify-between gap-4 rounded-xl bg-slate-50 p-3 text-xs"><div><b className="text-slate-700">{t.campaign}</b><p className="mt-1 text-slate-400">{new Date(t.created_at).toLocaleDateString()}</p></div><b className="text-[#070a45]">{t.currency} {t.amount.toFixed(2)}</b></div>)}</div>{statement.account.credit_used>0&&<div className="mt-4 space-y-2"><div className="grid gap-2 sm:grid-cols-3"><input className="field" type="number" min="0.01" step="0.01" max={statement.account.credit_used} value={settlementAmount} onChange={e=>setSettlementAmount(e.target.value)} placeholder={"Amount (max LSL "+statement.account.credit_used.toFixed(2)+")"}/><select className="field" value={settlementMethod} onChange={e=>setSettlementMethod(e.target.value)}><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="mobile_money">Mobile money</option><option value="card">Card</option></select><input className="field" value={settlementReference} onChange={e=>setSettlementReference(e.target.value)} placeholder="Payment reference (optional)"/></div><button type="button" onClick={settleAccount} className="primary">{settlementAmount?"Record partial payment":"Settle full balance"}</button></div>}{lastSettlementId&&<button type="button" onClick={downloadSettlementReceipt} className="mt-2 secondary">Download latest settlement receipt</button>}</div>}
    </section>
   </div>}
  </div>
  <style jsx>{".field{height:2.8rem;width:100%;border-radius:.75rem;border:1px solid #e2e8f0;padding:0 .75rem;font-size:.8125rem;outline:none}.primary,.secondary{height:2.8rem;width:100%;border-radius:.75rem;font-size:.8125rem;font-weight:800}.primary{background:#e31545;color:white}.secondary{background:#070a45;color:white}"}</style>
 </main>
}
function Header({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]">{icon}</div><h2 className="font-black text-[#070a45]">{title}</h2></div><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-black text-[#070a45]">{value}</p></div>}
