"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Loader2, XCircle } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Campaign={id:number;title:string;status:string;cancelled_at?:string|null;cancellation_reason?:string|null};

export default function CancelCampaignPage(){
  const router=useRouter(); const params=useParams<{id:string}>(); const id=Number(params.id);
  const [campaign,setCampaign]=useState<Campaign|null>(null); const [reason,setReason]=useState(""); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [done,setDone]=useState(false); const [refundId,setRefundId]=useState<number|null>(null);
  useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="advertiser"){router.replace("/login");return;}api<Campaign[]>("/api/v1/campaigns",{},true).then(rows=>{const row=rows.find(x=>x.id===id);if(!row)throw new Error("Campaign not found");setCampaign(row)}).catch(e=>setError(e.message));},[id,router]);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const result=await api<{refund_request_id?:number|null}>("/api/v1/campaigns/"+id+"/cancel",{method:"POST",body:JSON.stringify({reason})},true);setRefundId(result.refund_request_id||null);setDone(true);}catch(e){setError(e instanceof Error?e.message:"Unable to cancel campaign")}finally{setBusy(false)}}
  return <main className="min-h-screen bg-[#f0f2f5]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-3xl items-center gap-4 px-4 sm:px-6"><Link href="/advertiser" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div><h1 className="font-bold text-slate-900">Cancel Campaign</h1><p className="text-xs text-slate-500">Cancel an advert before publication.</p></div></div></header><div className="mx-auto max-w-3xl p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}{!campaign?<div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[#0866ff]"/></div>:done?<section className="rounded-xl border border-slate-200 bg-white p-6 sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-xl bg-slate-100 text-slate-600"><XCircle/></div><h2 className="mt-5 text-2xl font-bold text-slate-900">Campaign cancelled</h2><p className="mt-3 text-sm leading-6 text-slate-500">{refundId?"A refund request was created automatically because this campaign had a confirmed payment. Meloli staff will review it.":"The campaign is no longer eligible for payment, review, scheduling or publication."}</p><div className="mt-6 flex flex-wrap gap-2"><Link href="/advertiser" className="rounded-xl bg-[#070a45] px-4 py-3 text-sm font-semibold text-white">Back to campaigns</Link>{refundId&&<Link href="/advertiser/refunds" className="rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-900">Open refund request</Link>}</div></section>:<section className="rounded-xl border border-slate-200 bg-white p-6 sm:p-8"><p className="text-xs font-bold tracking-normal text-[#0866ff]">Campaign #{campaign.id}</p><h2 className="mt-2 text-2xl font-bold text-slate-900">{campaign.title}</h2><p className="mt-3 text-sm leading-6 text-slate-500">Once cancelled, this campaign will be blocked from payment, editorial review and publishing. If Meloli already confirmed a payment, a refund review case will be created automatically.</p><form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-sm font-bold text-slate-700">Reason for cancellation</span><textarea className="min-h-36 w-full rounded-xl border border-slate-200 p-4 text-sm outline-none focus:border-[#0866ff]" value={reason} onChange={e=>setReason(e.target.value)} minLength={5} required placeholder="Explain why you want to cancel this campaign..."/></label><button disabled={busy} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-rose-700 px-5 text-sm font-semibold text-white disabled:opacity-50">{busy&&<Loader2 size={16} className="animate-spin"/>}{busy?"Cancelling...":"Cancel campaign"}</button></form></section>}</div></main>
}