"use client";

import Link from "next/link";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CalendarDays, CheckCircle2, CircleDollarSign, Download, FileText, Loader2, ReceiptText } from "lucide-react";
import { API_URL, api, getSessionUser, getToken } from "@/lib/api";
import { useRealtimeTopics } from "@/app/components/RealtimeBridge";

type Plan={id:number;code:string;name:string;description:string;monthly_price:number;annual_price:number;currency:string;max_staff:number;max_campaigns_monthly:number;custom_domains:boolean;competition_certification:boolean};
type Payment={id:number;amount:number;currency:string;method:string;reference?:string|null;status:string;verification_code?:string|null;paid_at?:string|null};
type Invoice={id:number;invoice_number:string;plan_id:number;plan_name?:string|null;billing_period:string;amount:number;currency:string;status:string;due_at:string;paid_at?:string|null;created_at:string;payment?:Payment|null};

export default function TenantBillingPage(){
 const router=useRouter();
 const [plans,setPlans]=useState<Plan[]>([]);
 const [invoices,setInvoices]=useState<Invoice[]>([]);
 const [form,setForm]=useState({plan_id:0,billing_period:"monthly",payment_method:"bank_transfer",payment_reference:""});
 const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(""); const [error,setError]=useState(""); const [message,setMessage]=useState("");

 async function load(){setLoading(true);setError("");try{const [p,i]=await Promise.all([api<Plan[]>("/api/v1/tenant-plans"),api<Invoice[]>("/api/v1/tenant-admin/billing",{},true)]);setPlans(p);setInvoices(i);setForm(x=>({...x,plan_id:x.plan_id||p[0]?.id||0}));}catch(e){setError(e instanceof Error?e.message:"Unable to load billing")}finally{setLoading(false)}}
 useEffect(()=>{const u=getSessionUser();if(!u?.is_tenant_admin){router.replace("/advertiser");return;}load();},[router]);
 useRealtimeTopics(["tenant_billing","tenant"],()=>{load()});

 const selected=useMemo(()=>plans.find(p=>p.id===form.plan_id),[plans,form.plan_id]);
 const price=selected?(form.billing_period==="annual"?selected.annual_price:selected.monthly_price):0;

 async function checkout(e:FormEvent){e.preventDefault();setBusy("checkout");setError("");setMessage("");try{const row=await api<Invoice>("/api/v1/tenant-admin/billing/checkout",{method:"POST",body:JSON.stringify(form)},true);setMessage(`Invoice ${row.invoice_number} created. Payment confirmation will activate the subscription.`);setForm(x=>({...x,payment_reference:""}));await load();}catch(e){setError(e instanceof Error?e.message:"Unable to create checkout")}finally{setBusy("")}}

 async function download(path:string,filename:string){setBusy(filename);setError("");try{const token=getToken();const response=await fetch(API_URL+path,{headers:token?{Authorization:"Bearer "+token}:{}});if(!response.ok){let message="Unable to download document";try{message=(await response.json()).detail||message}catch{}throw new Error(message)}const blob=await response.blob();const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url);}catch(e){setError(e instanceof Error?e.message:"Unable to download document")}finally{setBusy("")}}

 return <main className="min-h-screen bg-[#f0f2f5] text-slate-900">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-6xl items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-bold text-slate-900">Page Subscription Billing</h1><p className="text-xs text-slate-500">Choose a platform plan, submit payment details, and keep branded invoices and receipts.</p></div><Link href="/tenant-admin/team" className="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-900">Team & onboarding</Link></div></header>
  <div className="mx-auto max-w-6xl space-y-6 p-4 sm:p-6 lg:p-8">
   {error&&<div className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}
   {message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-700">{message}</div>}
   {loading?<div className="grid min-h-64 place-items-center"><Loader2 className="animate-spin text-[#0866ff]"/></div>:<>
    <section className="grid gap-4 lg:grid-cols-3">{plans.map(plan=><button type="button" onClick={()=>setForm(x=>({...x,plan_id:plan.id}))} key={plan.id} className={"rounded-xl border bg-white p-5 text-left transition "+(form.plan_id===plan.id?"border-[#0866ff] ring-2 ring-[#070a45]/10":"border-slate-200 hover:border-slate-300")}><div className="flex items-center justify-between"><div><p className="text-xs font-bold tracking-normal text-[#0866ff]">{plan.code}</p><h2 className="mt-1 text-xl font-bold text-slate-900">{plan.name}</h2></div>{form.plan_id===plan.id&&<CheckCircle2 className="text-emerald-600"/>}</div><p className="mt-3 min-h-12 text-sm leading-6 text-slate-500">{plan.description}</p><div className="mt-5 flex items-end justify-between"><div><p className="text-2xl font-bold text-slate-900">{plan.currency} {plan.monthly_price.toLocaleString()}</p><p className="text-xs text-slate-400">per month</p></div><div className="text-right"><p className="text-sm font-semibold text-slate-700">{plan.max_staff} staff</p><p className="text-xs text-slate-400">{plan.max_campaigns_monthly} campaigns/month</p></div></div><div className="mt-4 flex flex-wrap gap-2 text-[10px] font-bold">{plan.custom_domains&&<span className="rounded-full bg-blue-50 px-2.5 py-1 text-blue-700">Custom domain</span>}{plan.competition_certification&&<span className="rounded-full bg-violet-50 px-2.5 py-1 text-violet-700">Competition certification</span>}</div></button>)}</section>

    <section className="grid gap-6 lg:grid-cols-[.85fr_1.15fr]">
     <form onSubmit={checkout} className="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#e7f3ff] text-slate-900"><CircleDollarSign size={19}/></div><div><h2 className="font-bold text-slate-900">Start or renew subscription</h2><p className="mt-1 text-sm text-slate-500">Creates a formal invoice and pending payment record.</p></div></div><div className="mt-5 space-y-4"><Field label="Billing period"><select value={form.billing_period} onChange={e=>setForm(x=>({...x,billing_period:e.target.value}))}><option value="monthly">Monthly</option><option value="annual">Annual</option></select></Field><Field label="Payment method"><select value={form.payment_method} onChange={e=>setForm(x=>({...x,payment_method:e.target.value}))}><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="mobile_money">Mobile money</option></select></Field><Field label="Payment / proof reference"><input value={form.payment_reference} onChange={e=>setForm(x=>({...x,payment_reference:e.target.value}))} placeholder="Bank, mobile-money or internal reference"/></Field><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center justify-between text-sm"><span className="font-bold text-slate-500">Selected plan</span><span className="font-semibold text-slate-900">{selected?.name||"—"}</span></div><div className="mt-2 flex items-end justify-between"><span className="text-xs text-slate-400">{form.billing_period==="annual"?"Annual subscription":"Monthly subscription"}</span><span className="text-2xl font-bold text-slate-900">{selected?.currency||"LSL"} {price.toLocaleString()}</span></div></div><button disabled={busy==="checkout"||!form.plan_id} className="h-12 w-full rounded-xl bg-[#070a45] text-sm font-semibold text-white disabled:opacity-50">{busy==="checkout"?"Creating invoice...":"Create subscription invoice"}</button></div></form>

     <div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-100 p-5 sm:p-6"><h2 className="font-bold text-slate-900">Billing history</h2><p className="mt-1 text-sm text-slate-500">Platform subscription invoices and confirmed receipts.</p></div>{invoices.length===0?<div className="p-10 text-center text-sm text-slate-500">No subscription invoices yet.</div>:<div className="divide-y divide-slate-100">{invoices.map(row=><div key={row.id} className="p-5 sm:px-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-900">{row.invoice_number}</p><Status value={row.status}/></div><p className="mt-1 text-sm text-slate-500">{row.plan_name||"Subscription"} · {row.billing_period}</p><p className="mt-1 text-xs text-slate-400">Due {new Date(row.due_at).toLocaleDateString()}</p></div><div className="text-left sm:text-right"><p className="text-xl font-bold text-slate-900">{row.currency} {row.amount.toLocaleString()}</p><p className="mt-1 text-xs text-slate-400">{row.payment?.reference||"No payment reference"}</p></div></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>download("/api/v1/tenant-billing/invoices/"+row.id+".pdf",row.invoice_number+".pdf")} className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-xs font-semibold text-slate-900"><FileText size={14}/> Invoice PDF</button>{row.payment?.status==="paid"&&<button onClick={()=>download("/api/v1/tenant-billing/payments/"+row.payment!.id+"/receipt.pdf","TSR-"+row.payment!.id+".pdf")} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-3 py-2 text-xs font-semibold text-white"><ReceiptText size={14}/> Receipt PDF</button>}{row.payment?.verification_code&&<span className="inline-flex items-center rounded-xl bg-slate-50 px-3 py-2 font-mono text-[10px] text-slate-500">Verify {row.payment.verification_code}</span>}</div></div>)}</div>}</div>
    </section>
   </>}
  </div>
 </main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-xs font-bold tracking-normal text-slate-500">{label}</span><div className="rounded-xl border border-slate-200 bg-slate-50 px-3 [&_input]:h-12 [&_input]:w-full [&_input]:bg-transparent [&_input]:text-sm [&_input]:outline-none [&_select]:h-12 [&_select]:w-full [&_select]:bg-transparent [&_select]:text-sm [&_select]:outline-none">{children}</div></label>}
function Status({value}:{value:string}){const cls=value==="paid"?"bg-emerald-50 text-emerald-700":value==="payment_rejected"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700";return <span className={"rounded-full px-2.5 py-1 text-[10px] font-bold "+cls}>{value.replaceAll("_"," ")}</span>}
