"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, CheckCircle2, Loader2, RefreshCw, RotateCcw, Send, XCircle } from "lucide-react";
import { api, getSessionUser } from "@/lib/api";

type Delivery={id:number;notification_id:number;channel:string;status:string;attempts:number;last_error?:string|null;sent_at?:string|null;created_at:string};

export default function NotificationDeliveryPage(){
 const router=useRouter(); const [rows,setRows]=useState<Delivery[]>([]); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState<number|string>(""); const [error,setError]=useState("");
 async function load(){setLoading(true);setError("");try{setRows(await api<Delivery[]>("/api/v1/admin/notification-deliveries",{},true));}catch(e){setError(e instanceof Error?e.message:"Unable to load delivery queue")}finally{setLoading(false)}}
 useEffect(()=>{const u=getSessionUser();if(!u||u.role!=="super_admin"){router.replace("/dashboard");return;}load();},[router]);
 const stats=useMemo(()=>({sent:rows.filter(r=>r.status==="sent").length,failed:rows.filter(r=>r.status==="failed").length,pending:rows.filter(r=>r.status==="pending").length}),[rows]);
 async function retry(id:number){setBusy(id);setError("");try{await api("/api/v1/admin/notification-deliveries/"+id+"/retry",{method:"POST"},true);await load();}catch(e){setError(e instanceof Error?e.message:"Retry reset failed")}finally{setBusy("")}}
 async function retryAll(){setBusy("all");setError("");try{await api("/api/v1/admin/notification-deliveries/retry-failed",{method:"POST"},true);await load();}catch(e){setError(e instanceof Error?e.message:"Unable to reset failed deliveries")}finally{setBusy("")}}
 return <main className="min-h-screen bg-[#f5f6fa] text-slate-900"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-20 max-w-[1450px] items-center gap-4 px-4 sm:px-6"><Link href="/dashboard" className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><ArrowLeft size={18}/></Link><div className="flex-1"><h1 className="font-black text-[#070a45]">Notification Delivery</h1><p className="text-xs text-slate-500">Email and webhook queue health, failures and retries.</p></div><button onClick={load} className="grid h-10 w-10 place-items-center rounded-xl border border-slate-200"><RefreshCw size={17}/></button></div></header><div className="mx-auto max-w-[1450px] p-4 sm:p-6 lg:p-8">{error&&<div className="mb-5 rounded-2xl border border-rose-200 bg-rose-50 p-4 text-sm font-semibold text-rose-700">{error}</div>}<div className="mb-6 grid gap-4 sm:grid-cols-3"><Metric icon={<CheckCircle2/>} label="Sent" value={stats.sent}/><Metric icon={<XCircle/>} label="Failed" value={stats.failed}/><Metric icon={<Send/>} label="Pending" value={stats.pending}/></div><div className="overflow-hidden rounded-[1.5rem] border border-slate-200 bg-white"><div className="flex flex-col gap-3 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-[#070a45]">Recent delivery attempts</h2><p className="mt-1 text-sm text-slate-500">The worker retries pending and failed records automatically up to its attempt limit.</p></div><button onClick={retryAll} disabled={busy==="all"||stats.failed===0} className="flex items-center gap-2 rounded-xl bg-[#070a45] px-4 py-3 text-xs font-extrabold text-white disabled:opacity-40"><RotateCcw size={15}/> Retry all failed</button></div>{loading?<div className="grid min-h-56 place-items-center"><Loader2 className="animate-spin text-[#e31545]"/></div>:rows.length===0?<div className="p-8 text-sm text-slate-500">No external notification deliveries have been queued yet.</div>:<div className="divide-y divide-slate-100">{rows.map(r=><div key={r.id} className="grid gap-3 p-5 sm:grid-cols-[.8fr_.8fr_.6fr_1.7fr_auto] sm:items-center"><div><p className="text-xs font-black uppercase tracking-wider text-slate-400">#{r.notification_id}</p><p className="mt-1 text-sm font-extrabold text-[#070a45]">{r.channel}</p></div><Status value={r.status}/><div className="text-xs font-bold text-slate-500">{r.attempts} attempt{r.attempts===1?"":"s"}</div><div className="min-w-0"><p className="truncate text-xs text-slate-500">{r.last_error|| (r.sent_at?"Delivered "+new Date(r.sent_at).toLocaleString():"Queued "+new Date(r.created_at).toLocaleString())}</p></div>{r.status==="failed"?<button onClick={()=>retry(r.id)} disabled={busy===r.id} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-extrabold text-[#070a45]">{busy===r.id?"Resetting...":"Retry"}</button>:<span/>}</div>)}</div>}</div></div></main>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:number}){return <div className="rounded-[1.4rem] border border-slate-200 bg-white p-5"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#070a45]/5 text-[#070a45]">{icon}</div><p className="mt-4 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black text-[#070a45]">{value}</p></div>}
function Status({value}:{value:string}){const cls=value==="sent"?"bg-emerald-50 text-emerald-700":value==="failed"?"bg-rose-50 text-rose-700":"bg-amber-50 text-amber-700";return <span className={"w-fit rounded-full px-3 py-1.5 text-xs font-extrabold "+cls}>{value}</span>}
